const groups = [
  { id:"select", name:"选择输入", hint:"从选项中做选择", items:[
    ["基础下拉","Select","选项少，只需要选一个值。","点击字段后在下方展开选项，选择后收起并显示结果。","做一个基础下拉 Select。点击字段后在下方展开选项；单击一项立即选中并收起，字段中显示选中值。"],
    ["可搜索下拉","Searchable Select","选项很多，用户知道要找什么。","输入关键词实时过滤，支持键盘选择和无结果状态。","做一个可搜索下拉。展开后聚焦搜索框，输入时过滤并高亮关键词，回车选中，Esc 关闭。"],
    ["级联选择","Cascader","选项有上下级，如省—市—区。","逐级展开；选中后显示完整路径。","做一个三级 Cascader，按省—市—区逐级展开；选中后显示完整路径，切换上级时清空失效的下级。"],
    ["多选下拉","Multi Select","一次选择多个筛选条件。","勾选后不收起；显示已选数量，并可一键清空。","做一个可搜索多选下拉。勾选后保持展开，顶部显示已选数量，并提供全选与清空。"],
    ["日期范围","Date Range","同时选择开始和结束日期。","高亮完整区间，并提供最近 7 天、30 天快捷项。","做一个日期范围选择器。先选开始日再选结束日，高亮整个区间，并提供最近 7 天和最近 30 天。"]
  ]},
  { id:"expand", name:"展开动画", hint:"让内容出现得自然", items:[
    ["圆点变胶囊","Circle to Pill","展示短状态或确认信息。","圆形入口平滑变宽，文字随后淡入。","点击圆形按钮后，让它从中心平滑扩展成胶囊；保留图标，文字随后淡入，300ms 后稳定。"],
    ["手风琴展开","Accordion","在当前位置查看更多内容。","内容向下展开，箭头同步旋转，再次点击收起。","点击标题行后向下展开正文，高度与透明度同时过渡，右侧箭头旋转 180 度。"],
    ["下推展开","Push Down","详情属于页面结构，不应遮住内容。","新内容进入文档流，平滑推开下方内容。","点击查看详情后，在当前卡片下方展开内容并平滑推开后续区域，滚动位置保持不变。"],
    ["分段展开","Staggered Reveal","一组项目按顺序进入。","项目依次淡入并轻微上移，整组控制在 500ms 内。","面板展开时，列表项从上到下依次淡入并上移 8px，每项间隔 40ms。"]
  ]},
  { id:"drag", name:"拖拽操作", hint:"移动、排序或调整", items:[
    ["排序拖拽","Sortable","改变同一列表里的顺序。","拖动项浮起，原位保留占位，松手后保存顺序。","列表项按住后可拖动排序；拖动项浮起，原位置显示虚线占位，松手后保存并提供撤销。"],
    ["跨区移动","Transfer","把卡片移动到另一个状态或容器。","目标区域高亮，不可放置处显示禁用。","支持卡片在三列看板间拖动；进入目标列时高亮落点，松手后更新状态。"],
    ["自由画布","Free Move","调整节点在画布里的位置。","靠近其他节点时显示参考线并吸附，不能拖出边界。","让节点可在画布内自由拖动，接近其他节点时显示对齐线并吸附，不得拖出画布。"],
    ["调整尺寸","Resize","改变卡片、列或面板大小。","显示拖拽把手和实时尺寸，设置最小最大值。","在卡片右下角提供缩放把手，拖动时显示宽高并吸附栅格，限制最小和最大尺寸。"]
  ]},
  { id:"panel", name:"面板弹层", hint:"补充信息或完成任务", items:[
    ["提示气泡","Tooltip","悬停时补充一句解释，不承载操作。","贴近目标，自动避让边缘，移开后消失。","悬停图标后在上方显示两行以内的 Tooltip，自动避让窗口边缘，移开或失焦后消失。"],
    ["操作气泡","Popover","在触发点附近放少量信息或操作。","点击外部或按 Esc 关闭。","点击头像后在下方打开 Popover，显示三个快捷操作；点击外部或按 Esc 关闭。"],
    ["右侧抽屉","Drawer","不离开当前页，查看或编辑较长内容。","从右侧滑入；说明宽度、遮罩和关闭方式。","点击详情后，从页面右侧滑入宽 360px 的 Drawer；标题固定、内容滚动，关闭后焦点回到入口。"],
    ["底部面板","Bottom Sheet","移动端展示选项或连续操作。","从底部出现，可下拉关闭，并适配安全区域。","移动端点击筛选后，从底部弹出 Bottom Sheet；可拖动调整高度，下拉超过阈值关闭。"],
    ["模态弹窗","Modal","必须先确认或填写才能继续。","锁定背景，焦点留在弹窗内，主次按钮清楚。","点击删除后打开居中 Modal，遮罩并锁定背景；默认聚焦取消按钮，确认后显示处理结果。"]
  ]},
  { id:"nav", name:"导航结构", hint:"切换内容与层级", items:[
    ["标签页","Tabs","切换同级内容。","当前项高亮，切换时不刷新整个页面。","在内容区顶部放 Tabs，点击后切换概览、数据、成员；当前项高亮，不刷新整页。"],
    ["步骤条","Stepper","展示流程进度和下一步。","区分已完成、当前与未开始状态。","表单顶部显示三步 Stepper，区分已完成、当前和未开始；提交后推进，并允许返回已完成步骤。"],
    ["面包屑","Breadcrumb","说明当前位置和页面层级。","前级可返回；当前页只显示、不链接。","标题上方显示首页—项目—报表的 Breadcrumb；前两级可返回，当前页加粗且不可点击。"],
    ["折叠侧边栏","Collapsible Sidebar","承载长期稳定的主导航，同时节省空间。","展开显示文字，收起只留图标，并记住用户状态。","在左侧做宽 240px 的可折叠侧边栏；收起后宽 64px 只留图标，悬停显示名称，当前页持续高亮。"],
    ["锚点目录","Anchor Nav","在长页面章节间快速定位。","滚动时同步高亮当前章节。","长页面右侧放锚点目录，点击平滑滚动到章节；滚动时自动高亮当前项。"]
  ]},
  { id:"loading", name:"加载反馈", hint:"告诉用户正在发生什么", items:[
    ["骨架屏","Skeleton","结构已知，内容还在请求。","占位对应真实结构；完成后淡入内容，避免布局跳动。","数据卡加载时显示与标题、指标和图表结构一致的 Skeleton；数据返回后淡入真实内容。"],
    ["进度条","Progress Bar","任务进度可以计算。","显示比例与当前阶段；失败时保留重试。","导入文件时显示进度条、百分比和当前阶段；失败时停在失败点并提供重试。"],
    ["按钮加载","Loading Button","提交动作正在执行。","按钮宽度不变，并禁用重复提交。","提交后按钮保持原宽度，显示加载状态和“提交中”；结束后短暂显示结果。"],
    ["局部加载","Inline Loader","只更新一个卡片或表格区域。","只阻塞受影响区域，其他内容保持可用。","刷新图表时只在图表区域显示半透明 Loader，筛选区和其他卡片仍可操作。"]
  ]},
  { id:"chart", name:"图表交互", hint:"探索、比较和下钻数据", items:[
    ["十字线","Crosshair","精准读取同一位置的时间与数值。","横纵辅助线跟随鼠标，并吸附最近的数据点。","鼠标移入折线图后显示横纵辅助线，交点吸附最近数据点；同时显示时间和数值，移出后消失。","读数与提示"],
    ["提示框","Chart Tooltip","在不打断阅读时补充详细数值。","跟随目标，显示名称、时间、数值和必要说明。","悬停数据点时，在旁边显示名称、时间、数值和同比变化；提示框自动避让边缘。","读数与提示"],
    ["图例筛选","Legend Filter","隐藏或恢复系列，减少比较干扰。","关闭项变灰，坐标轴保持稳定，再点一次恢复。","点击图例时隐藏或显示对应系列；关闭项变灰，剩余曲线保留，坐标轴范围不跳动。","选择与聚焦"],
    ["框选与缩放","Brush & Zoom","选一段数据并放大查看。","拖动形成半透明选区，松手后更新主图或明细。","按住鼠标拖动选择时间范围；松手后放大主图并筛选下方明细，提供恢复全部按钮。","范围与导航"],
    ["数据下钻","Drill Down","从汇总进入下一层明细。","图表更新，同时显示层级路径和返回入口。","点击地区柱子后进入城市明细；更新标题和面包屑，并提供返回上一级按钮。","探索与联动"],
    ["点选高亮","Point Selection","锁定一个数据点继续查看或操作。","点击点后保持高亮，空白处清除选择。","点击散点后锁定选中状态并显示详情；点击空白处清除，选中点要有明显描边。","选择与聚焦"],
    ["多选对比","Multi Selection","同时比较多个离散对象。","逐项加入或移出选择集，并实时汇总已选对象。","点击柱子切换多选状态；保留已选项高亮，在顶部显示已选名称和合计值。","选择与聚焦"],
    ["套索选择","Lasso Selection","散点密集且需要圈出不规则区域。","拖动画出自由选区，命中的点高亮，其余点弱化。","在散点图上拖动形成套索区域；松手后高亮区域内的数据点并显示选中数量，支持清除。","选择与聚焦"],
    ["平移与缩放","Pan & Zoom","时间序列很长，需要查看局部并前后移动。","滚轮或按钮缩放，拖动平移，并始终显示当前范围。","为长时间序列提供放大、缩小、左右平移和重置；交互后同步显示当前可见时间范围。","范围与导航"],
    ["时间范围滑块","Range Slider","快速改变看板的统计时间窗口。","拖动双端范围条，主图和范围文案同步更新。","在趋势图下方放双端时间范围滑块；拖动任一端时实时更新主图和起止日期，禁止两端交叉。","范围与导航"],
    ["联动高亮","Linked Highlight","在多个视图中识别同一对象。","悬停或点击一个类别时，所有图表同步强调对应数据。","悬停任一渠道柱子时，同时高亮趋势图中的同渠道曲线和明细标签，其余对象降低透明度。","探索与联动"],
    ["跨图筛选","Cross Filter","通过一个图表筛选整张分析看板。","选择维度值后，其他图表重新聚合，并提供清除筛选。","点击地区柱子后，用该地区筛选渠道占比、趋势和总量；顶部显示筛选条件并提供一键清除。","探索与联动"],
    ["焦点与上下文","Focus + Context","放大局部，同时保留它在全局中的位置。","上方显示细节，下方小图保留全局并控制窗口。","使用上下双图：主图展示选中时间段，底部概览图保留全量数据；拖动窗口同步改变主图范围。","范围与导航"],
    ["基准线与标注","Annotation","解释目标、异常或关键事件。","阈值线持续可见，点击数据点可添加或删除注释。","在图表中显示目标基准线；点击数据点添加文字标注，再次点击删除，标注不要遮挡数据。","解释与输出"],
    ["对比模式","Compare Mode","比较两个周期、版本或人群的变化。","选择基准与当前范围，并突出显示差值而非只画两条线。","提供本期与对比期选择；切换后同时更新两条趋势和差值标签，颜色区分但保持同一坐标尺度。","解释与输出"],
    ["图表表格切换","Chart / Table","既要快速看趋势，也要读取或复制精确数据。","在同一数据源上切换图表和表格，筛选状态保持不变。","提供图表与数据表两种视图；切换时保持当前筛选和排序，表格支持读取精确值。","解释与输出"],
    ["固定提示框","Pinned Tooltip","需要保留某个点的信息，再和其他数据比较。","点击数据点固定提示，再点另一个点切换，点击空白处关闭。","点击数据点后固定 Tooltip，允许移动鼠标继续查看其他位置；点击另一点更新固定内容，点击空白处关闭。","读数与提示"],
    ["共享游标","Shared Cursor","多个时间序列图需要读取同一时刻。","一个面板中的游标同步到其他面板，并统一显示时间。","在多个时间序列面板间同步十字线；鼠标进入任一图表时，所有图表显示相同时间位置的辅助线和数值。","读数与提示"],
    ["时间播放","Time Playback","数据随时间演变，如地图、排名和运营趋势。","播放头按时间推进，可暂停、拖动和调整速度。","为时间序列增加播放、暂停和时间滑块；播放时逐帧更新图表与日期，允许拖动到任意时间点。","范围与导航"],
    ["交互历史","Undo / Reset","探索中经过多次筛选和缩放，需要返回之前状态。","记录关键交互，支持撤销、重做和一键复位。","记录图表的缩放、平移和筛选状态；提供撤销、重做、恢复初始视图，并正确禁用不可用按钮。","范围与导航"],
    ["层级缩放","Hierarchy Zoom","树图、旭日图或矩形树图层级较深。","点击父节点放大其子层级，保留返回路径。","点击层级节点后放大到其子节点并更新面包屑；点击面包屑返回上层，保持颜色映射一致。","探索与联动"],
    ["邻居聚焦","Neighbor Focus","关系网络中需要查看一个节点的直接关系。","选择节点后突出它及相邻连线，其余节点淡化。","点击关系图节点后高亮该节点、直接邻居和相连边；其他元素降低透明度，点击空白处恢复。","探索与联动"],
    ["流向追踪","Flow Trace","桑基图或路径图中需要理解来源与去向。","悬停节点时突出完整上游、下游或整条路径。","悬停桑基图节点时高亮与它相连的上游和下游路径，并在旁边汇总流入、流出数值。","探索与联动"],
    ["地图拾取","Map Picking","在地图上查看区域或点位详情。","悬停高亮区域，点击后固定信息并保持地图上下文。","地图区域支持悬停高亮和点击选择；选中后显示区域名称与指标，点击空白处清除。","探索与联动"],
    ["详情跳转","Data Link","从指标或数据点跳到相关页面继续处理。","携带当前维度与筛选上下文打开详情，返回后状态不丢失。","点击数据点显示详情入口；跳转时携带日期、地区和指标参数，返回看板后恢复原筛选状态。","探索与联动"],
    ["键盘浏览","Keyboard Navigation","保证不使用鼠标也能读取图表。","方向键在数据点间移动，回车选择，Esc 清除。","让图表数据点可通过 Tab 聚焦、方向键切换、Enter 选择、Esc 清除，并提供清晰焦点样式和读数。","选择与聚焦"],
    ["参数模拟","What-if Control","观察目标、预算或转化率变化对结果的影响。","调整参数后立即重算预测值，并明确区分输入与预测。","提供参数滑块控制预算；拖动时实时更新预测收入和变化率，并标明这是模拟结果而非实际值。","解释与输出"],
    ["维度切换","Dimension Switch","在地区、渠道、品类等分析角度之间切换。","切换后重组分类轴，指标和其他筛选保持不变。","在图表上方提供维度切换器，可在地区、渠道、品类间切换；保持当前指标和时间范围，平滑更新分类轴与数据。","重构与切换"],
    ["指标切换","Metric Switch","在同一分析视角下查看收入、订单量等不同指标。","单位、刻度和数值随指标同步更新，当前选择清楚可见。","为图表提供指标切换器；切换收入、订单量和转化率时，同步更新标题、单位、刻度和数据，并保留其他筛选。","重构与切换"],
    ["聚合粒度","Time Granularity","按日、周、月观察不同尺度的趋势。","切换粒度后重新聚合，时间范围不丢失。","提供日、周、月粒度切换；根据当前时间范围重新聚合趋势，更新横轴标签和点数，不改变筛选条件。","重构与切换"],
    ["选区联动明细","Brush to Details","从图表圈选一段范围，立即核对对应明细。","选区变化时，下方明细表只展示命中记录并显示数量。","在趋势图中拖动框选时间范围；松手后筛选下方明细表，显示命中记录数，并提供清除选区。","探索与联动"],
    ["数据标签开关","Data Label Toggle","在概览和精确读数之间快速切换。","按需显示关键点数值，避免默认标签遮挡图形。","提供数据标签开关；开启时只显示末值、峰值和异常点的标签，关闭后恢复简洁图表。","解释与输出"]
  ]},
  { id:"table", name:"数据表格", hint:"浏览、核对和处理明细", items:[
    ["列排序","Column Sort","按某一字段快速找到高值、低值或最新记录。","点击表头在升序、降序和默认顺序间切换。","表格列头支持三态排序：默认、升序、降序；显示明确方向图标，并保持其他筛选条件。"],
    ["列筛选","Column Filter","只查看某一列中符合条件的记录。","筛选入口靠近列名，生效后显示条件和结果数量。","在状态列头提供筛选菜单；选择条件后仅显示匹配行，列头显示已筛选状态，并提供清除。"],
    ["行选择与批量操作","Bulk Selection","一次处理多条记录。","勾选行后出现批量操作栏，明确已选数量。","表格支持逐行勾选和全选；有选中项时显示批量操作栏与数量，操作完成后清空选择。"],
    ["展开行","Expandable Row","不离开列表查看一条记录的补充信息。","详情紧邻当前行展开，再次点击收起。","点击行首展开按钮，在当前行下方展示负责人、更新时间和备注；再次点击收起，同时只展开一行。"],
    ["行内编辑","Inline Edit","快速修改少量字段，不值得打开完整表单。","双击或点击编辑进入输入态，保存与取消结果清楚。","点击单元格进入行内编辑；提供保存和取消，校验失败时就地提示，保存后立即显示新值。"],
    ["列宽调整","Column Resize","长文本和数字列需要不同显示宽度。","拖动表头分隔线调整列宽，并限制最小宽度。","在表头右边缘提供拖拽手柄；拖动时实时改变列宽并显示宽度，限制最小值，松手后保留设置。"],
    ["冻结列","Sticky Column","横向滚动宽表时仍要识别每一行。","关键列固定在左侧，滚动区与固定区边界清晰。","将名称列冻结在表格左侧；横向滚动其他指标列时名称保持可见，并用细阴影提示冻结边界。"],
    ["分页与每页数量","Pagination","数据量大，需要分批浏览并控制单页密度。","页码、总数和每页数量保持同步，切换后回到表格顶部。","表格底部显示总条数、页码和每页数量；切页或改变每页数量后更新数据，并回到表格顶部。"]
  ]},
  { id:"filter", name:"筛选视图", hint:"缩小范围并保存分析上下文", items:[
    ["快捷筛选","Quick Filter","常用条件少，用户需要一键切换。","用短标签直接切换，当前条件持续高亮。","在列表上方放常用快捷筛选：全部、进行中、已完成；点击即生效，当前项高亮并更新结果数。"],
    ["条件构建器","Filter Builder","需要组合多个字段和逻辑条件。","每条条件包含字段、关系和值，并明确 AND 或 OR。","提供高级筛选条件构建器；每行包含字段、运算符和值，可增加或删除条件，并切换 AND、OR 逻辑。"],
    ["全局筛选栏","Global Filter Bar","同一组条件要控制整张看板。","条件固定在看板顶部，所有卡片同步更新。","在看板顶部放全局筛选栏，日期、地区和渠道共同控制所有图表；变化时显示正在更新和结果范围。"],
    ["已用条件标签","Applied Filters","筛选较多，需要随时知道当前范围。","每个条件独立可移除，并提供一键清空。","把已生效筛选显示为可移除标签；删除任一标签立即更新结果，并提供清空全部，空状态显示全部数据。"],
    ["保存视图","Saved View","经常重复使用同一套筛选和排序。","保存当前条件并可一键恢复，清楚区分默认与自定义视图。","允许把当前筛选、排序和列配置保存为命名视图；点击视图即可恢复，支持设为默认和删除。"],
    ["相对时间","Relative Time","监控场景需要随当前时间滚动的范围。","最近 15 分钟、24 小时等范围会自动前移。","提供相对时间选择器，支持最近 15 分钟、1 小时、24 小时和 7 天；显示自动刷新状态与下一次更新时间。"],
    ["筛选重置提醒","Dirty Filter State","用户修改了条件但还没应用，容易误以为数据已更新。","区分草稿与已生效条件，应用和重置按钮只在有变化时可用。","筛选面板内区分未应用修改与当前生效条件；有变化时启用应用和重置，应用后更新结果并清除未保存状态。"]
  ]},
  { id:"dashboard", name:"看板布局", hint:"让数据更清晰而非更花", items:[
    ["极简数据板","Minimal","管理层总览与日常监控。","大留白、细分隔、单一强调色。","做一个极简 Dashboard：浅色背景、细分隔线、一个强调色；先指标、再趋势、最后明细。"],
    ["便当盒布局","Bento Grid","信息模块多、优先级不同。","统一栅格，用卡片面积表达优先级。","用 Bento Grid 排列看板；核心指标占大卡片，其余模块按统一间距对齐，避免装饰性阴影。"],
    ["深色监控台","Dark Ops","实时监控和异常发现。","深背景、高对比状态色，严格控制发光效果。","做一个深色实时监控台；仅异常和告警使用高亮色，其他数据使用低饱和中性色。"],
    ["高密度分析","High Density","专业用户需要同时查看大量数据。","紧凑表格、小倍图和联动筛选，仍保持统一对齐。","做一个高密度分析看板，用紧凑表格、小倍图和顶部联动筛选；所有模块严格对齐到同一栅格。"]
  ]}
];

let currentGroup = 0;
let currentItem = 0;
const categoryGrid = document.querySelector("#category-nav");
const primaryTabs = document.querySelector("#primary-tabs");
const detail = document.querySelector("#detail");
const locationTree = [
  {name:"浙江省",children:[{name:"杭州市",children:["西湖区","滨江区","余杭区"]},{name:"宁波市",children:["海曙区","鄞州区","北仑区"]}]},
  {name:"广东省",children:[{name:"广州市",children:["天河区","越秀区","海珠区"]},{name:"深圳市",children:["南山区","福田区","宝安区"]}]},
  {name:"江苏省",children:[{name:"南京市",children:["鼓楼区","建邺区","秦淮区"]},{name:"苏州市",children:["姑苏区","吴中区","工业园区"]}]},
  {name:"四川省",children:[{name:"成都市",children:["锦江区","武侯区","高新区"]},{name:"绵阳市",children:["涪城区","游仙区"]}]},
  {name:"湖南省",children:[{name:"长沙市",children:["岳麓区","芙蓉区","雨花区"]},{name:"株洲市",children:["天元区","芦淞区"]}]},
  {name:"北京市",children:[{name:"北京市",children:["朝阳区","海淀区","东城区"]}]},
  {name:"上海市",children:[{name:"上海市",children:["浦东新区","徐汇区","静安区"]}]}
];
const locationPaths=locationTree.flatMap(province=>province.children.flatMap(city=>city.children.map(area=>[province.name,city.name,area])));
const pathButtons=(paths=locationPaths.slice(0,5))=>paths.map(path=>`<button type="button" data-path="${path.join("|")}"><b>${path.at(-1)}</b><small>${path.join(" / ")}</small></button>`).join("");
const initialCascade=()=>`<div class="cascade-col provinces">${locationTree.map((province,index)=>`<button class="${index===0?'chosen':''}">${province.name}<b>›</b></button>`).join('')}</div><div class="cascade-col cities">${locationTree[0].children.map((city,index)=>`<button class="${index===0?'chosen':''}">${city.name}<b>›</b></button>`).join('')}</div><div class="cascade-col areas">${locationTree[0].children[0].children.map((area,index)=>`<button class="${index===0?'chosen':''}">${area}</button>`).join('')}</div>`;
const searchIndex=groups.flatMap((group,groupIndex)=>group.items.map((item,itemIndex)=>({groupIndex,itemIndex,group:group.name,name:item[0],en:item[1],when:item[2],category:item[5]||group.hint})));
const favoriteKey="dp-component-favorites";
const recentKey="dp-component-recent";
let favorites=new Set(JSON.parse(localStorage.getItem(favoriteKey)||"[]"));
let recent=JSON.parse(localStorage.getItem(recentKey)||"[]");
const taskQueries={选择:"选择",筛选:"筛选",比较:"比较 对比",详情:"详情 展开 提示",状态:"状态 加载 进度",布局:"看板 布局",收藏:"__favorites__",最近:"__recent__"};
const itemId=(groupIndex=currentGroup,itemIndex=currentItem)=>`${groupIndex}-${itemIndex}`;
const comboNames={select:["全局筛选栏","已用条件标签"],expand:["右侧抽屉","骨架屏"],drag:["交互历史","按钮加载"],panel:["按钮加载","步骤条"],nav:["面包屑","保存视图"],loading:["局部加载","筛选重置提醒"],chart:["跨图筛选","数据表格","保存视图"],table:["列筛选","保存视图","行选择与批量操作"],filter:["已用条件标签","保存视图","全局筛选栏"],dashboard:["全局筛选栏","跨图筛选","详情跳转"]};

function demo(type, item) {
  const key=`${type}-${item}`;
  const demos={
    "select-0":`<button class="ui-select trigger" type="button">请选择地区 <b>⌄</b></button><div class="ui-menu"><button>北京市</button><button>上海市</button><button>广东省</button></div>`,
    "select-1":`<div class="search-select"><label><span>⌕</span><input aria-label="搜索地区" placeholder="搜索省、市或区"></label><div class="search-options">${pathButtons()}</div></div><p class="demo-result">输入“深圳”或“南山”试试</p>`,
    "select-2":`<div class="cascader-shell"><label><span>⌕</span><input class="cascade-search" aria-label="搜索省市区" placeholder="搜索省、市或区"></label><div class="cascade-matches"></div><div class="cascader">${initialCascade()}</div></div><p class="demo-result">请选择省、市、区</p>`,
    "select-3":`<div class="multi-select"><div class="multi-field"><div class="multi-tags"><span>华东 ×</span><span>华南 ×</span></div><b>已选 2 项</b></div><div class="check-list"><button data-value="华东" class="checked">✓ 华东</button><button data-value="华南" class="checked">✓ 华南</button><button data-value="华北">华北</button><button data-value="西南">西南</button><button class="clear-multi">清空</button></div></div>`,
    "select-4":`<div class="quick-range"><button>最近 7 天</button><button>最近 30 天</button></div><div class="calendar">${Array.from({length:14},(_,i)=>`<button>${i+1}</button>`).join("")}</div><p class="demo-result">请选择开始日期</p>`,
    "expand-0":`<button class="pill-toggle" type="button"><i></i><span>已保存</span></button>`,
    "expand-1":`<div class="accordion-demo"><button class="accordion-head">订单明细 <b>⌄</b></button><div class="accordion-body"><p>商品金额　¥ 1,280</p><p>优惠金额　− ¥ 80</p></div></div>`,
    "expand-2":`<div class="push-stack"><div class="push-card"><button>查看详情</button><div class="push-detail">本月转化率提升 12%，主要来自自然流量。</div></div><div class="push-card muted-card">下一项内容</div></div>`,
    "expand-3":`<button class="reveal-trigger">展开成员</button><div class="reveal-list"><span>林晓 · 产品</span><span>陈晨 · 设计</span><span>周可 · 数据</span></div>`,
    "drag-0":`<div class="sortable-list"><button>⠿　需求评审</button><button>⠿　交互设计</button><button>⠿　开发排期</button></div><p class="demo-result">拖动条目调整顺序</p>`,
    "drag-1":`<div class="transfer-board"><div class="dropzone"><b>待处理</b><button class="move-card">用户反馈 #42</button></div><div class="dropzone"><b>处理中</b></div><div class="dropzone"><b>已完成</b></div></div>`,
    "drag-2":`<div class="free-canvas"><span class="guide-x"></span><span class="guide-y"></span><button class="free-node">指标卡</button><button class="fixed-node">趋势图</button></div>`,
    "drag-3":`<div class="resize-box"><b>可调整卡片</b><span class="size-label">180 × 100</span><button class="resize-handle" aria-label="调整尺寸"></button></div>`,
    "panel-0":`<div class="tooltip-stage"><button class="info-target">?</button><div class="tooltip-bubble">统计周期内的去重用户数</div></div>`,
    "panel-1":`<div class="popover-stage"><button class="avatar">YC</button><div class="popover-card"><b>言川</b><button>查看资料</button><button>发送消息</button></div></div>`,
    "panel-2":`<div class="mini-page"><button class="open-layer">查看详情</button></div><div class="drawer-layer"><button class="close-layer">×</button><b>项目详情</b><p>负责人　林晓</p><p>状态　进行中</p></div>`,
    "panel-3":`<div class="mini-page"><button class="open-layer">筛选</button><p class="sheet-result">全部项目</p></div><div class="sheet-layer"><i></i><b>选择筛选条件</b><button data-filter="仅看进行中">仅看进行中</button><button data-filter="仅看我负责">仅看我负责</button><button class="close-sheet">取消</button></div>`,
    "panel-4":`<div class="mini-page"><button class="open-layer danger">删除项目</button></div><div class="modal-mask"><div class="modal-card"><b>确认删除？</b><p>删除后无法恢复。</p><button class="cancel">取消</button><button class="confirm">确认删除</button></div></div>`,
    "nav-0":`<div class="tabs-demo"><div><button class="active">概览</button><button>数据</button><button>成员</button></div><p>概览内容</p></div>`,
    "nav-1":`<div class="stepper-demo"><ol><li class="done">1 基本信息</li><li class="current">2 配置权限</li><li>3 完成</li></ol><button>下一步</button></div>`,
    "nav-2":`<nav class="crumb-demo"><button>首页</button><i>›</i><button>项目</button><i>›</i><b>销售看板</b></nav><p class="demo-result">销售看板</p>`,
    "nav-3":`<div class="collapse-nav"><button class="nav-toggle">☰</button><button class="active" data-page="概览"><i>⌂</i><span>概览</span></button><button data-page="数据分析"><i>▥</i><span>数据分析</span></button><button data-page="设置"><i>⚙</i><span>设置</span></button></div><div class="nav-main">概览内容</div>`,
    "nav-4":`<div class="anchor-page"><div><section>01 概览</section><section>02 趋势</section><section>03 明细</section></div><nav><button class="active">概览</button><button>趋势</button><button>明细</button></nav></div>`,
    "loading-0":`<div class="skeleton-card"><div class="sk-title"></div><div class="sk-number"></div><div class="sk-chart"></div><div class="loaded-content"><span>本月收入</span><b>¥ 128,600</b><i></i></div></div>`,
    "loading-1":`<div class="progress-demo"><b>正在导入数据</b><div><i></i></div><span>0%</span><button>重新播放</button></div>`,
    "loading-2":`<button class="loading-button"><i></i><span>提交报表</span></button><p class="demo-result">点击按钮提交</p>`,
    "loading-3":`<div class="inline-layout"><div class="filter-row"><button data-values="近 30 天|近 7 天|今天">近 30 天</button><button data-values="全部渠道|自然流量|付费投放">全部渠道</button></div><div class="inline-card"><svg viewBox="0 0 240 80"><path d="M5 65L55 42L105 53L155 20L235 32"/></svg><div class="inline-loader">加载中…</div></div></div>`,
    "chart-0":chartMarkup("line"),
    "chart-1":`<div class="bar-chart"><button style="--h:45%" data-value="一月 · 42 万"></button><button style="--h:72%" data-value="二月 · 68 万"></button><button style="--h:58%" data-value="三月 · 55 万"></button><div class="chart-tip">二月 · 68 万</div></div>`,
    "chart-2":`<div class="legend-demo"><div class="legend-row"><button data-series="a">● 订单量</button><button data-series="b">● 成交额</button></div><svg viewBox="0 0 300 130"><path class="series-a" d="M10 95L65 65L120 78L180 32L235 55L290 20"/><path class="series-b" d="M10 110L65 90L120 48L180 72L235 38L290 58"/></svg></div>`,
    "chart-3":`<div class="brush-demo"><svg viewBox="0 0 300 130"><path d="M8 100L50 84L92 92L134 45L176 68L218 35L292 52"/></svg><div class="brush-range"></div><button>恢复全部</button></div>`,
    "chart-4":`<div class="drill-demo"><div class="drill-crumb"><button>全国</button><span></span></div><div class="drill-bars"><button data-region="华东" style="--h:82%">华东</button><button data-region="华南" style="--h:64%">华南</button><button data-region="华北" style="--h:48%">华北</button></div></div>`,
    "chart-5":`<div class="point-select-chart"><svg viewBox="0 0 300 170">${[[38,112],[76,72],[118,98],[158,48],[205,82],[248,35],[270,118]].map(([x,y],i)=>`<circle data-point="${i}" cx="${x}" cy="${y}" r="7"/>`).join('')}</svg><div class="selection-info">点击一个点查看详情</div></div>`,
    "chart-6":`<div class="multi-bar-chart"><div class="selection-summary">尚未选择</div><div class="multi-bars"><button data-name="华东" data-value="86" style="--h:86%">华东</button><button data-name="华南" data-value="68" style="--h:68%">华南</button><button data-name="华北" data-value="52" style="--h:52%">华北</button><button data-name="西南" data-value="44" style="--h:44%">西南</button></div></div>`,
    "chart-7":`<div class="lasso-chart"><svg viewBox="0 0 300 170">${[[32,112],[58,68],[82,132],[104,86],[132,52],[160,118],[185,74],[214,40],[244,96],[270,62]].map(([x,y],i)=>`<circle data-point="${i}" cx="${x}" cy="${y}" r="6"/>`).join('')}</svg><div class="lasso-box"></div><button class="clear-selection">清除选择</button><span class="selection-count">已选 0 个点</span></div>`,
    "chart-8":`<div class="panzoom-chart"><div class="chart-toolbar"><button data-action="out">−</button><button data-action="in">＋</button><button data-action="left">‹</button><button data-action="right">›</button><button data-action="reset">重置</button></div><div class="panzoom-window"><svg viewBox="0 0 600 150"><path d="M5 112L55 82L105 100L155 45L205 66L255 30L305 72L355 42L405 88L455 55L505 74L595 25"/></svg></div><p>当前范围：1 月 — 6 月</p></div>`,
    "chart-9":`<div class="range-chart"><svg viewBox="0 0 300 120"><path d="M5 92L45 74L85 84L125 42L165 62L205 28L245 52L295 20"/></svg><div class="dual-range"><input aria-label="开始月份" type="range" min="1" max="11" value="3"><input aria-label="结束月份" type="range" min="2" max="12" value="10"></div><p>3 月 — 10 月</p></div>`,
    "chart-10":`<div class="linked-charts"><div class="linked-bars"><button data-link="a" style="--h:78%">自然</button><button data-link="b" style="--h:58%">投放</button><button data-link="c" style="--h:42%">活动</button></div><svg viewBox="0 0 180 100"><path data-link="a" d="M5 75L45 55L90 62L130 28L175 38"/><path data-link="b" d="M5 88L45 72L90 42L130 60L175 48"/><path data-link="c" d="M5 94L45 85L90 74L130 78L175 62"/></svg></div>`,
    "chart-11":`<div class="crossfilter-demo"><div class="filter-chip">全部地区</div><div class="filter-bars"><button data-filter="华东" style="--h:82%">华东</button><button data-filter="华南" style="--h:65%">华南</button><button data-filter="华北" style="--h:48%">华北</button></div><div class="filter-summary"><b>总量 286 万</b><i style="--w:76%"></i><i style="--w:58%"></i></div><button class="clear-filter">清除筛选</button></div>`,
    "chart-12":`<div class="focus-context"><div class="focus-title">主图 · 3 月至 9 月</div><div class="focus-window"><svg viewBox="0 0 420 100"><path d="M5 78L55 52L105 68L155 30L205 48L255 20L305 55L355 35L415 42"/></svg></div><div class="context-track"><i class="context-selection"></i></div></div>`,
    "chart-13":`<div class="annotation-chart"><div class="target-line"><span>目标 80</span></div><svg viewBox="0 0 300 150">${[[38,104],[92,72],[148,88],[205,38],[260,62]].map(([x,y],i)=>`<circle data-label="${['起点','增长','回落','峰值','当前'][i]}" cx="${x}" cy="${y}" r="7"/>`).join('')}<path d="M38 104L92 72L148 88L205 38L260 62"/></svg><div class="annotation-note">点击数据点添加标注</div></div>`,
    "chart-14":`<div class="compare-chart"><div class="compare-controls"><button data-period="同比">同比</button><button data-period="环比">环比</button></div><svg viewBox="0 0 300 140"><path class="current-line" d="M10 108L65 72L120 86L180 42L235 58L290 28"/><path class="base-line" d="M10 118L65 98L120 76L180 82L235 67L290 62"/></svg><div class="delta-label">本期较同比 +12.4%</div></div>`,
    "chart-15":`<div class="view-switch"><div class="view-tabs"><button data-view="chart" class="active">图表</button><button data-view="table">表格</button></div><div class="chart-view"><div style="--h:48%"></div><div style="--h:78%"></div><div style="--h:62%"></div></div><table class="table-view"><thead><tr><th>月份</th><th>收入</th></tr></thead><tbody><tr><td>一月</td><td>42 万</td></tr><tr><td>二月</td><td>68 万</td></tr><tr><td>三月</td><td>55 万</td></tr></tbody></table></div>`,
    "chart-16":`<div class="pinned-chart"><svg viewBox="0 0 300 160">${[[40,110,42],[92,76,58],[150,94,49],[208,42,82],[265,68,67]].map(([x,y,v],i)=>`<circle data-month="${i+1}月" data-value="${v}万" cx="${x}" cy="${y}" r="7"/>`).join('')}<path d="M40 110L92 76L150 94L208 42L265 68"/></svg><div class="pinned-tip">点击数据点固定提示</div></div>`,
    "chart-17":`<div class="shared-cursor"><div class="sync-panel"><b>成交额</b><svg viewBox="0 0 280 80"><path d="M5 65L55 42L105 54L160 20L220 38L275 12"/></svg><i></i></div><div class="sync-panel"><b>订单量</b><svg viewBox="0 0 280 80"><path d="M5 58L55 62L105 34L160 48L220 22L275 36"/></svg><i></i></div><span>4 月</span></div>`,
    "chart-18":`<div class="playback-chart"><div class="playback-bars">${[42,58,76,64,88].map((v,i)=>`<i style="--h:${v}%" data-step="${i}"></i>`).join('')}</div><div class="playback-controls"><button class="play-toggle">▶</button><input aria-label="时间进度" type="range" min="0" max="4" value="0"><b>1 月</b></div></div>`,
    "chart-19":`<div class="history-chart"><div class="history-tools"><button data-history="undo" disabled>撤销</button><button data-history="redo" disabled>重做</button><button data-history="reset">复位</button></div><div class="history-bars"><button data-value="华东" style="--h:82%">华东</button><button data-value="华南" style="--h:64%">华南</button><button data-value="华北" style="--h:48%">华北</button></div><p>初始视图</p></div>`,
    "chart-20":`<div class="hierarchy-chart"><div class="hierarchy-crumb"><button data-level="root">全部业务</button><span></span></div><div class="treemap"><button data-node="电商" class="tree-a">电商</button><button data-node="广告" class="tree-b">广告</button><button data-node="服务" class="tree-c">服务</button></div></div>`,
    "chart-21":`<div class="network-chart"><svg viewBox="0 0 300 180"><path data-edge="ab" d="M70 90L150 45"/><path data-edge="ac" d="M70 90L155 135"/><path data-edge="bd" d="M150 45L240 82"/><circle data-node="a" cx="70" cy="90" r="17"/><circle data-node="b" cx="150" cy="45" r="14"/><circle data-node="c" cx="155" cy="135" r="14"/><circle data-node="d" cx="240" cy="82" r="14"/><text x="62" y="94">A</text><text x="145" y="49">B</text><text x="150" y="139">C</text><text x="235" y="86">D</text></svg><p>点击节点查看直接关系</p></div>`,
    "chart-22":`<div class="flow-chart"><svg viewBox="0 0 300 170"><path data-flow="a" d="M45 45C115 45 110 65 175 65S235 45 270 45"/><path data-flow="b" d="M45 125C115 125 110 90 175 90S235 125 270 125"/><rect data-node="source" x="25" y="25" width="28" height="120"/><rect data-node="middle" x="162" y="48" width="28" height="65"/><rect data-node="target" x="260" y="25" width="28" height="120"/></svg><p>总流量 286 万</p></div>`,
    "chart-23":`<div class="map-picking"><svg viewBox="0 0 300 170"><path data-region="华北" d="M72 30l55 5 14 42-48 22-42-28z"/><path data-region="华东" d="M142 48l68-12 36 35-18 55-67-2-20-47z"/><path data-region="华南" d="M132 126l96 0-18 29-58 4z"/></svg><div class="map-tip">点击区域查看指标</div></div>`,
    "chart-24":`<div class="data-link-chart"><div class="link-bars"><button data-detail="华东" style="--h:82%">华东</button><button data-detail="华南" style="--h:64%">华南</button><button data-detail="华北" style="--h:48%">华北</button></div><div class="detail-link"><span>选择数据点查看详情入口</span><button disabled>查看明细 →</button></div></div>`,
    "chart-25":`<div class="keyboard-chart" tabindex="0" role="application" aria-label="可使用方向键浏览的数据图表"><div class="keyboard-bars">${['一月','二月','三月','四月','五月'].map((m,i)=>`<button data-index="${i}" style="--h:${[44,66,52,82,70][i]}%">${m}</button>`).join('')}</div><p>使用 ← → 移动，Enter 选择，Esc 清除</p></div>`,
    "chart-26":`<div class="whatif-chart"><label>预算 <b>50 万</b><input aria-label="模拟预算" type="range" min="20" max="100" value="50"></label><div class="forecast-card"><span>预测收入</span><strong>150 万</strong><em>模拟结果 · ROI 3.0</em></div></div>`,
    "chart-27":`<div class="switch-chart dimension-switch"><div class="switch-tabs"><button class="active" data-dimension="地区">地区</button><button data-dimension="渠道">渠道</button><button data-dimension="品类">品类</button></div><div class="switch-bars">${[78,56,42].map((v,i)=>`<button style="--h:${v}%"><i></i><span>${['华东','华南','华北'][i]}</span></button>`).join('')}</div><p>成交额 · 按地区</p></div>`,
    "chart-28":`<div class="switch-chart metric-switch"><div class="switch-tabs"><button class="active" data-metric="收入">收入</button><button data-metric="订单量">订单量</button><button data-metric="转化率">转化率</button></div><div class="metric-readout"><span>当前指标 · 收入</span><b>286 万元</b></div><svg viewBox="0 0 300 100"><path d="M5 82L55 58L105 70L155 30L210 46L295 18"/></svg></div>`,
    "chart-29":`<div class="granularity-chart"><div class="switch-tabs"><button data-grain="日">日</button><button class="active" data-grain="周">周</button><button data-grain="月">月</button></div><div class="grain-bars">${[38,56,45,74,62,88,70].map(v=>`<i style="--h:${v}%"></i>`).join('')}</div><p>近 8 周 · 共 8 个数据点</p></div>`,
    "chart-30":`<div class="brush-details"><div class="mini-brush"><svg viewBox="0 0 300 95"><path d="M5 76L55 54L105 65L155 26L210 42L295 16"/></svg><div class="brush-window"></div></div><div class="detail-rows"><span><b>日期</b><b>收入</b></span><span>05-12 <em>46 万</em></span><span>05-13 <em>58 万</em></span></div><p>拖动上方图表框选明细</p></div>`,
    "chart-31":`<div class="label-toggle-chart"><div class="label-head"><span>渠道收入</span><button aria-pressed="false">显示关键标签</button></div><div class="label-bars">${[['自然',78],['投放',56],['活动',88],['推荐',48]].map(([n,v])=>`<div style="--h:${v}%"><b>${v}</b><i></i><span>${n}</span></div>`).join('')}</div></div>`,
    "table-0":`<div class="data-table-demo sort-table"><table><thead><tr><th>地区</th><th><button data-sort>收入 <i>↕</i></button></th><th>订单</th></tr></thead><tbody>${[['华东',286,1842],['华南',192,1260],['华北',168,980]].map(r=>`<tr data-value="${r[1]}"><td>${r[0]}</td><td>${r[1]} 万</td><td>${r[2]}</td></tr>`).join('')}</tbody></table><p>点击“收入”排序</p></div>`,
    "table-1":`<div class="data-table-demo filter-table"><div class="table-filter-head"><b>项目列表</b><button>状态：全部 ⌄</button></div><div class="filter-menu"><button data-status="全部">全部</button><button data-status="进行中">进行中</button><button data-status="已完成">已完成</button></div><table><tbody><tr data-status="进行中"><td>增长分析</td><td><i>进行中</i></td></tr><tr data-status="已完成"><td>渠道复盘</td><td><i>已完成</i></td></tr><tr data-status="进行中"><td>留存专题</td><td><i>进行中</i></td></tr></tbody></table><p>共 3 条</p></div>`,
    "table-2":`<div class="data-table-demo bulk-table"><div class="bulk-bar"><span>选择记录后可批量操作</span><button disabled>批量归档</button></div><table><tbody>${['增长分析','渠道复盘','留存专题'].map((n,i)=>`<tr><td><input aria-label="选择${n}" type="checkbox"></td><td>${n}</td><td>${['进行中','已完成','待处理'][i]}</td></tr>`).join('')}</tbody></table></div>`,
    "table-3":`<div class="data-table-demo expand-table"><table><tbody>${['增长分析','渠道复盘'].map((n,i)=>`<tr class="main-row"><td><button data-row="${i}">›</button></td><td>${n}</td><td>${i?'已完成':'进行中'}</td></tr><tr class="row-detail" data-detail-row="${i}"><td colspan="3">负责人：${i?'陈晨':'林晓'}　·　更新于今天</td></tr>`).join('')}</tbody></table><p>点击行首箭头查看详情</p></div>`,
    "table-4":`<div class="data-table-demo edit-table"><table><thead><tr><th>项目</th><th>负责人</th><th></th></tr></thead><tbody><tr><td>增长分析</td><td class="editable-value">林晓</td><td><button class="edit-cell">编辑</button></td></tr></tbody></table><div class="edit-actions"><input aria-label="负责人" value="林晓"><button data-edit="save">保存</button><button data-edit="cancel">取消</button></div><p>点击编辑修改负责人</p></div>`,
    "table-5":`<div class="data-table-demo resize-table"><div class="resize-table-wrap"><div class="resize-col"><b>项目名称</b><button aria-label="调整列宽"></button></div><div><b>收入</b></div><div><b>状态</b></div><div class="cell">增长分析报告</div><div class="cell">286 万</div><div class="cell">进行中</div></div><p>拖动表头分隔线 · 140 px</p></div>`,
    "table-6":`<div class="data-table-demo sticky-table"><div class="wide-table"><table><thead><tr><th>业务线</th>${['收入','订单','用户','转化率','客单价'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${['电商','广告','服务'].map((n,i)=>`<tr><td>${n}</td>${[286,1842,42000,'6.8%',155].map((x,j)=>`<td>${typeof x==='number'?x-i*23:x}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>横向滚动，业务线保持可见</p></div>`,
    "table-7":`<div class="data-table-demo page-table"><table><tbody><tr><td>增长分析</td><td>进行中</td></tr><tr><td>渠道复盘</td><td>已完成</td></tr><tr><td>留存专题</td><td>待处理</td></tr></tbody></table><div class="pagination"><span>共 24 条</span><button data-page="prev">‹</button><b>1 / 8</b><button data-page="next">›</button></div></div>`,
    "filter-0":`<div class="filter-demo quick-filter"><div><button class="active" data-quick="全部">全部</button><button data-quick="进行中">进行中</button><button data-quick="已完成">已完成</button></div><ul><li data-status="进行中">增长分析 <i>进行中</i></li><li data-status="已完成">渠道复盘 <i>已完成</i></li><li data-status="进行中">留存专题 <i>进行中</i></li></ul><p>共 3 条</p></div>`,
    "filter-1":`<div class="filter-demo builder-filter"><div class="logic-toggle"><button class="active">AND</button><button>OR</button></div><div class="condition"><button data-values="地区|渠道|状态">地区</button><button data-values="等于|不等于|包含">等于</button><button data-values="华东|华南|华北">华东</button><button class="remove-condition">×</button></div><button class="add-condition">＋ 添加条件</button><p>符合全部 1 条条件</p></div>`,
    "filter-2":`<div class="filter-demo global-filter"><div class="global-controls"><button data-values="近 30 天|近 7 天|今天">近 30 天</button><button data-values="全国|华东|华南">全国</button><button data-values="全部渠道|自然流量|付费投放">全部渠道</button></div><div class="global-cards"><article><span>收入</span><b>286 万</b></article><article><span>订单</span><b>1,842</b></article></div><p>全部数据 · 近 30 天</p></div>`,
    "filter-3":`<div class="filter-demo applied-filter"><div class="filter-tags"><button data-tag>地区：华东 ×</button><button data-tag>渠道：自然 ×</button><button data-tag>状态：进行中 ×</button></div><button class="clear-tags">清空全部</button><div class="filter-result"><b>86</b><span>条匹配记录</span></div></div>`,
    "filter-4":`<div class="filter-demo saved-view"><div class="saved-list"><button class="active" data-view-name="我的默认视图">我的默认视图 <i>默认</i></button><button data-view-name="华东周报">华东周报</button><button data-view-name="待跟进项目">待跟进项目</button></div><button class="save-current">＋ 保存当前视图</button><p>地区：全国 · 近 30 天</p></div>`,
    "filter-5":`<div class="filter-demo relative-time"><div class="time-options"><button data-time="15 分钟">最近 15 分钟</button><button class="active" data-time="1 小时">最近 1 小时</button><button data-time="24 小时">最近 24 小时</button><button data-time="7 天">最近 7 天</button></div><div class="refresh-state"><i></i><span>自动刷新中 · 范围随时间滚动</span></div></div>`,
    "filter-6":`<div class="filter-demo dirty-filter"><div class="dirty-head"><b>筛选条件</b><span>已应用：全国</span></div><div class="dirty-options"><button data-draft="华东">华东</button><button data-draft="华南">华南</button><button data-draft="华北">华北</button></div><div class="dirty-actions"><button data-dirty="reset" disabled>重置</button><button data-dirty="apply" disabled>应用</button></div><p>当前显示全国数据</p></div>`,
    "dashboard-0":`<div class="minimal-dash"><header>业务概览 <button data-values="近 30 天⌄|近 7 天⌄|今天⌄">近 30 天⌄</button></header><div><button class="metric-card"><span>成交额</span><b>¥ 2.86M</b><em>+12.4%</em></button><button class="metric-card"><span>订单量</span><b>18,492</b><em>+6.8%</em></button></div><svg viewBox="0 0 300 70"><path d="M5 62L55 50L105 55L155 28L205 38L250 12L295 22"/></svg></div>`,
    "dashboard-1":`<div class="bento-dash"><button class="wide">核心指标<b>¥ 2.86M</b></button><button>转化率<b>6.8%</b></button><button>用户数<b>42K</b></button><button class="long">趋势分析</button></div>`,
    "dashboard-2":`<div class="ops-dash"><header>实时监控 <i></i></header><div><button>服务可用率<b>99.98%</b></button><button class="alert">异常任务<b>3</b></button></div><p>流量 1,248 req/s　 延迟 32ms</p></div>`,
    "dashboard-3":`<div class="dense-dash"><div class="dense-filters"><button data-values="渠道：全部|渠道：自然流量|渠道：付费投放">渠道：全部</button><button data-values="地区：全国|地区：华东|地区：华南">地区：全国</button></div><table><thead><tr><th>业务线</th><th>收入</th><th>同比</th></tr></thead><tbody><tr><td>电商</td><td>286万</td><td>+12%</td></tr><tr><td>广告</td><td>192万</td><td>+8%</td></tr><tr><td>服务</td><td>86万</td><td>−2%</td></tr></tbody></table></div>`
  };
  return `<div class="demo component-demo" data-demo="${key}"><div class="demo-scene">${demos[key]}</div></div>`;
}

function chartMarkup(){
  return `<div class="cross-chart"><svg viewBox="0 0 300 150"><path class="chart-grid" d="M10 35H290M10 75H290M10 115H290"/><path class="chart-line" d="M10 118L65 90L120 102L180 48L235 70L290 28"/><circle cx="180" cy="48" r="5"/></svg><i class="cross-x"></i><i class="cross-y"></i><div class="cross-tip">4月 · 82万</div></div>`;
}

function render() {
  recent=[itemId(),...recent.filter(id=>id!==itemId())].slice(0,8);localStorage.setItem(recentKey,JSON.stringify(recent));
  const group=groups[currentGroup];
  primaryTabs.innerHTML=groups.map((tab,index)=>`<button type="button" data-group="${index}" aria-selected="${index===currentGroup}"><span>${tab.name}</span><small>${tab.items.length}</small></button>`).join('');
  requestAnimationFrame(()=>primaryTabs.querySelector('[aria-selected="true"]')?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'}));
  categoryGrid.innerHTML=`<div class="subnav ${group.id==='chart'?'grouped':''}" aria-label="${group.name}组件">${group.items.map((item,itemIndex)=>`${group.id==='chart'&&(itemIndex===0||item[5]!==group.items[itemIndex-1]?.[5])?`<p class="subnav-label">${item[5]}</p>`:''}<button class="item" type="button" data-item="${itemIndex}" aria-selected="${itemIndex===currentItem}">${item[0]}</button>`).join("")}</div>`;
  document.querySelector('#sidebar-title').textContent=group.name;
  document.querySelector("#section-kicker").textContent=group.id.toUpperCase();
  document.querySelector("#section-title").textContent=group.name;
  document.querySelector("#section-hint").textContent=group.hint;
  const [name,en,when,effect,prompt]=group.items[currentItem];
  const flat=searchIndex.findIndex(entry=>entry.groupIndex===currentGroup&&entry.itemIndex===currentItem),previous=searchIndex[flat-1],next=searchIndex[flat+1];
  const related=searchIndex.filter(item=>item.category===(group.items[currentItem][5]||group.hint)&&!(item.groupIndex===currentGroup&&item.itemIndex===currentItem)).slice(0,3);
  const combos=(comboNames[group.id]||[]).map(combo=>searchIndex.find(item=>item.name===combo)).filter(Boolean);
  detail.innerHTML=`<div class="detail-copy"><div class="detail-topline"><p class="detail-kicker">${en.toUpperCase()}</p><button class="favorite" type="button" aria-pressed="${favorites.has(itemId())}">${favorites.has(itemId())?'★ 已收藏':'☆ 收藏'}</button></div><h3>${name}</h3><p class="summary">${when}</p><div class="keyline"><b>效果</b><span>${effect}</span></div><div class="prompt-box"><span>AI 指令 <button class="copy" type="button">复制</button></span><p>${prompt}</p></div>${combos.length?`<div class="related combo"><b>常用组合</b>${combos.map(item=>`<button data-go="${item.groupIndex}-${item.itemIndex}">${item.name}</button>`).join('')}</div>`:''}${related.length?`<div class="related"><b>相似模式</b>${related.map(item=>`<button data-go="${item.groupIndex}-${item.itemIndex}">${item.name}</button>`).join('')}</div>`:''}<div class="detail-pager">${previous?`<button data-go="${previous.groupIndex}-${previous.itemIndex}"><small>上一个</small>${previous.name}</button>`:'<span></span>'}${next?`<button data-go="${next.groupIndex}-${next.itemIndex}"><small>下一个</small>${next.name}</button>`:'<span></span>'}</div></div><div class="demo-wrap"><div class="demo-label"><span>效果预览</span><div class="demo-switch"><button type="button" data-mode="auto" aria-selected="true">动画演示</button><button type="button" data-mode="manual" aria-selected="false">自己试试</button></div></div><div class="demo-slot">${demo(group.id,currentItem)}</div><p class="manual-tip">正在自动演示这个组件的核心动作</p></div>`;
  primaryTabs.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{currentGroup=Number(button.dataset.group);currentItem=0;render();document.querySelector('.sidebar').scrollTop=0;}));
  categoryGrid.querySelectorAll(".item").forEach(button=>button.addEventListener("click",()=>{currentItem=Number(button.dataset.item);render();}));
  detail.querySelector(".copy").addEventListener("click",()=>copyText(prompt));
  detail.querySelector(".favorite").addEventListener("click",()=>{const id=itemId();favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem(favoriteKey,JSON.stringify([...favorites]));render();});
  detail.querySelectorAll("[data-mode]").forEach(button=>button.addEventListener("click",()=>setDemoMode(button.dataset.mode)));
  detail.querySelectorAll("[data-go]").forEach(button=>button.addEventListener("click",()=>{[currentGroup,currentItem]=button.dataset.go.split('-').map(Number);render();window.scrollTo({top:document.querySelector('.content').offsetTop-75,behavior:'smooth'});}));
}

function setDemoMode(mode){
  detail.querySelectorAll("[data-mode]").forEach(button=>button.setAttribute("aria-selected",String(button.dataset.mode===mode)));
  const slot=detail.querySelector(".demo-slot"), type=groups[currentGroup].id;
  slot.innerHTML=demo(type,currentItem);
  const demoEl=slot.querySelector(".demo"), tip=detail.querySelector(".manual-tip"), key=demoEl.dataset.demo;
  if(mode==="auto"){tip.textContent="正在自动演示这个组件的核心动作";return;}
  demoEl.classList.add("manual-demo");
  bindManualDemo(demoEl,key,tip);
}

function bindManualDemo(root,key,tip){
  const $=selector=>root.querySelector(selector), $$=selector=>[...root.querySelectorAll(selector)];
  const say=text=>tip.textContent=text;
  const toggle=(selector,className="open")=>$(selector)?.classList.toggle(className);
  const instructions={select:["点击下拉框选择地区","输入省、市或区进行匹配","依次点击省、市、区，或直接搜索","点击选项添加、移除或清空","点击开始日和结束日"],expand:["点击圆点展开状态","点击标题展开或收起正文","点击查看详情，观察下方内容被推开","点击按钮，查看列表依次进入"],drag:["拖动条目调整顺序","把卡片拖到另一列，也可以直接点目标列","拖动画布中的指标卡","拖动右下角把手调整大小"],panel:["悬停或点击问号查看提示","点击头像打开操作气泡","点击查看详情打开右侧抽屉","点击筛选打开底部面板","点击删除项目打开确认弹窗"],nav:["点击标签切换同级内容","点击下一步推进流程","点击前级面包屑返回","点击菜单按钮收起或展开侧栏","点击目录定位章节"],loading:["点击卡片切换加载与完成状态","点击重新播放进度","点击按钮模拟提交","点击图表区域局部刷新"],chart:["在图表内移动鼠标读取数值","悬停或点击柱子查看数值","点击图例隐藏或恢复数据系列","在图表中横向拖动框选范围","点击地区进入下一层明细","点击数据点锁定或清除选择","点击多个柱子进行汇总对比","在散点图中拖出选择区域","使用工具栏平移、缩放或重置","拖动两个滑块改变时间范围","悬停或点击渠道联动两个图表","点击地区筛选整张迷你看板","拖动底部窗口改变主图范围","点击数据点添加或移除标注","切换同比与环比查看差值","切换图表与表格读取同一数据","点击数据点固定提示框","在任一面板移动鼠标同步游标","播放、暂停或拖动时间进度","执行筛选后尝试撤销、重做或复位","点击矩形进入下一层级","点击节点聚焦直接邻居","悬停节点追踪上下游路径","悬停或点击地图区域","选择数据点后进入相关明细","先聚焦图表，再使用方向键和回车","拖动预算滑块查看预测结果","切换地区、渠道或品类维度","切换指标并观察单位和数值","切换日、周、月聚合粒度","在趋势图中拖动选区联动明细","打开或关闭关键数据标签"],table:["点击收入列头切换排序","打开状态筛选并选择条件","勾选多行后执行批量操作","点击行首箭头展开详情","编辑负责人并保存或取消","拖动项目名称列右侧分隔线","横向滚动并观察冻结列","点击上一页或下一页"],filter:["点击快捷条件筛选列表","切换逻辑、字段或增加条件","切换顶部条件联动全部卡片","逐个移除条件或全部清空","选择视图或保存当前配置","选择滚动时间范围","修改条件后应用或重置"],dashboard:["点击指标查看重点状态","点击卡片切换重点模块","点击异常任务查看告警状态","点击筛选器切换分析范围"]};
  const [type,indexText]=key.split("-"), index=Number(indexText); say(instructions[type][index]);

  if(key==="select-0"){$(".trigger").onclick=()=>toggle(".ui-menu");$$('.ui-menu button').forEach(b=>b.onclick=()=>{$('.trigger').firstChild.textContent=`${b.textContent} `;toggle('.ui-menu');say(`已选择：${b.textContent}`);});}
  if(key==="select-1"){const input=$("input"),options=$(".search-options"),result=$(".demo-result");const bindResults=paths=>{options.innerHTML=paths.length?pathButtons(paths):'<p class="empty">没有匹配地区</p>';$$('.search-options button').forEach(b=>b.onclick=()=>{const path=b.dataset.path.split('|');input.value=path.at(-1);result.textContent=`已选择：${path.join(' / ')}`;say(`已选择：${path.at(-1)}`);});};input.oninput=()=>{const keyword=input.value.trim().toLowerCase(),matches=keyword?locationPaths.filter(path=>path.join(' ').toLowerCase().includes(keyword)):locationPaths.slice(0,5);bindResults(matches);result.textContent=keyword?(matches.length?`找到 ${matches.length} 个地区`:'没有匹配地区'):'输入“深圳”或“南山”试试';say(matches.length?`找到 ${matches.length} 个结果`:'没有匹配地区');};bindResults(locationPaths.slice(0,5));input.focus();}
  if(key==="select-2") bindCascader(root,say);
  if(key==="select-3"){const selected=new Set(['华东','华南']),renderTags=()=>{$('.multi-tags').innerHTML=[...selected].map(value=>`<span data-value="${value}">${value} ×</span>`).join('');$('.multi-field b').textContent=`已选 ${selected.size} 项`;$$('.multi-tags span').forEach(tag=>tag.onclick=()=>{selected.delete(tag.dataset.value);renderTags();syncChecks();say(`已移除：${tag.dataset.value}`);});},syncChecks=()=>{$$('.check-list [data-value]').forEach(b=>{const checked=selected.has(b.dataset.value);b.classList.toggle('checked',checked);b.textContent=`${checked?'✓ ':''}${b.dataset.value}`;});};$$('.check-list [data-value]').forEach(b=>b.onclick=()=>{selected.has(b.dataset.value)?selected.delete(b.dataset.value):selected.add(b.dataset.value);syncChecks();renderTags();say(`当前已选 ${selected.size} 项`);});$('.clear-multi').onclick=()=>{selected.clear();syncChecks();renderTags();say('已清空所有选项');};renderTags();}
  if(key==="select-4"){let start=null;const days=$$('.calendar button'),setRange=(a,z)=>{days.forEach(x=>{const n=Number(x.textContent);x.classList.toggle('range',n>=a&&n<=z);x.classList.toggle('edge',n===a||n===z);});$('.demo-result').textContent=`已选择：${a} 日 — ${z} 日`;say(`已选择 ${z-a+1} 天`);};days.forEach(b=>b.onclick=()=>{const day=Number(b.textContent);if(start===null){start=day;days.forEach(x=>x.classList.remove('range','edge'));b.classList.add('edge');$('.demo-result').textContent=`开始日：${day} 日，请选择结束日`;say(`开始日期：${day} 日`);}else{setRange(Math.min(start,day),Math.max(start,day));start=null;}});$$('.quick-range button').forEach((b,i)=>b.onclick=()=>setRange(i?1:8,14));}
  if(key==="expand-0"){$('.pill-toggle').onclick=()=>{toggle('.pill-toggle','open');say($('.pill-toggle').classList.contains('open')?'状态已展开':'状态已收起');};}
  if(key==="expand-1"){$('.accordion-head').onclick=()=>{toggle('.accordion-demo');say($('.accordion-demo').classList.contains('open')?'订单明细已展开':'订单明细已收起');};}
  if(key==="expand-2"){$('.push-card button').onclick=()=>{toggle('.push-stack');say($('.push-stack').classList.contains('open')?'详情已展开，下方内容被推开':'详情已收起');};}
  if(key==="expand-3"){$('.reveal-trigger').onclick=()=>{toggle('.reveal-list','open');say($('.reveal-list').classList.contains('open')?'成员已依次展开':'成员已收起');};}
  if(key==="drag-0") makeSortable($('.sortable-list'),say);
  if(key==="drag-1"){const card=$('.move-card');makeDraggable(card,root,(x)=>{const zones=$$('.dropzone');const zone=zones.find(z=>{const r=z.getBoundingClientRect();return x>=r.left&&x<=r.right;});if(zone){zone.append(card);say(`已移动到：${zone.querySelector('b').textContent}`);}});$$('.dropzone').forEach(z=>z.onclick=e=>{if(e.target===z||e.target.tagName==='B'){z.append(card);say(`已移动到：${z.querySelector('b').textContent}`);}});}
  if(key==="drag-2") makeFreeMove($('.free-node'),$('.free-canvas'),say);
  if(key==="drag-3") makeResize($('.resize-box'),$('.resize-handle'),say);
  if(key==="panel-0"){$('.info-target').onclick=()=>toggle('.tooltip-stage');}
  if(key==="panel-1"){$('.avatar').onclick=()=>toggle('.popover-stage');$$('.popover-card button').forEach(b=>b.onclick=()=>{say(`已选择：${b.textContent}`);$('.popover-stage').classList.remove('open');});}
  if(type==="panel"&&index>=2){$('.open-layer').onclick=()=>{root.classList.add('open');say('已打开，可点击关闭或完成操作');};$('.close-layer')?.addEventListener('click',()=>root.classList.remove('open'));$('.cancel')?.addEventListener('click',()=>root.classList.remove('open'));$('.confirm')?.addEventListener('click',()=>{root.classList.remove('open');say('项目已删除（演示）');});}
  if(key==="panel-3"){$$('[data-filter]').forEach(b=>b.onclick=()=>{$('.sheet-result').textContent=b.dataset.filter;root.classList.remove('open');say(`筛选已生效：${b.dataset.filter}`);});$('.close-sheet').onclick=()=>{root.classList.remove('open');say('已取消筛选');};}
  if(key==="nav-0"){$$('.tabs-demo button').forEach(b=>b.onclick=()=>{$$('.tabs-demo button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('.tabs-demo p').textContent=`${b.textContent}内容`;say(`已切换到：${b.textContent}`);});}
  if(key==="nav-1"){let step=2;$('.stepper-demo button').onclick=()=>{step=step===3?1:step+1;$$('.stepper-demo li').forEach((li,i)=>{li.className=i+1<step?'done':i+1===step?'current':'';});say(`当前第 ${step} 步`);};}
  if(key==="nav-2"){$$('.crumb-demo button').forEach(b=>b.onclick=()=>{$('.demo-result').textContent=b.textContent;say(`已返回：${b.textContent}`);});}
  if(key==="nav-3"){$('.nav-toggle').onclick=()=>{toggle('.collapse-nav','collapsed');say($('.collapse-nav').classList.contains('collapsed')?'侧栏已收起':'侧栏已展开');};$$('.collapse-nav [data-page]').forEach(b=>b.onclick=()=>{$$('.collapse-nav [data-page]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('.nav-main').textContent=`${b.dataset.page}内容`;say(`已切换到：${b.dataset.page}`);});}
  if(key==="nav-4"){$$('.anchor-page nav button').forEach((b,i)=>b.onclick=()=>{$$('.anchor-page nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('.anchor-page section').parentElement.style.transform=`translateY(-${i*72}px)`;say(`已定位到：${b.textContent}`);});}
  if(key==="loading-0"){$('.skeleton-card').onclick=()=>{toggle('.skeleton-card','complete');say($('.skeleton-card').classList.contains('complete')?'真实内容已淡入':'重新显示骨架结构');};}
  if(key==="loading-1"){$('.progress-demo button').onclick=()=>runProgress(root,say);}
  if(key==="loading-2"){$('.loading-button').onclick=()=>{const b=$('.loading-button');if(b.classList.contains('loading'))return;b.classList.add('loading');b.querySelector('span').textContent='提交中';say('正在提交，请稍候…');setTimeout(()=>{b.classList.remove('loading');b.classList.add('success');b.querySelector('span').textContent='提交成功';say('提交成功');},900);};}
  if(key==="loading-3"){$('.inline-card').onclick=()=>{$('.inline-loader').classList.add('show');say('只刷新当前图表，筛选仍可操作');setTimeout(()=>{$('.inline-loader').classList.remove('show');say('图表刷新完成');},900);};bindCycleButtons($$('.filter-row [data-values]'),say);}
  if(key==="chart-0"){const chart=$('.cross-chart');chart.onpointermove=e=>{const r=chart.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;root.style.setProperty('--mx',`${x}px`);root.style.setProperty('--my',`${y}px`);root.classList.add('tracking');$('.cross-tip').textContent=`${Math.max(1,Math.round(x/r.width*12))}月 · ${Math.round((1-y/r.height)*90+20)}万`;};chart.onpointerleave=()=>root.classList.remove('tracking');}
  if(key==="chart-1"){$$('.bar-chart button').forEach(b=>{const show=()=>{$('.chart-tip').textContent=b.dataset.value;$('.chart-tip').style.left=`${b.offsetLeft+b.offsetWidth/2}px`;};b.onpointerenter=show;b.onclick=show;});}
  if(key==="chart-2"){$$('.legend-row button').forEach(b=>b.onclick=()=>{b.classList.toggle('off');root.classList.toggle(`hide-${b.dataset.series}`);say(`${b.textContent.replace('● ','')}已${b.classList.contains('off')?'隐藏':'恢复'}`);});}
  if(key==="chart-3") makeBrush($('.brush-demo'),say);
  if(key==="chart-4"){$$('.drill-bars button').forEach(b=>b.onclick=()=>drill(root,b.dataset.region,say));$('.drill-crumb button').onclick=()=>setDemoMode('manual');}
  if(key==="chart-5"){$$('[data-point]').forEach((point,i)=>point.onclick=()=>{const active=point.classList.toggle('selected');$$('[data-point]').forEach(other=>{if(other!==point)other.classList.remove('selected');});$('.selection-info').textContent=active?'已选择数据点 '+(i+1)+' · 数值 '+(48+i*7):'点击一个点查看详情';say(active?'数据点已锁定':'选择已清除');});$('.point-select-chart').onclick=e=>{if(e.target.tagName==='svg'){$$('[data-point]').forEach(p=>p.classList.remove('selected'));$('.selection-info').textContent='点击一个点查看详情';}};}
  if(key==="chart-6"){$$('.multi-bars button').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');const selected=$$('.multi-bars .selected'),total=selected.reduce((sum,item)=>sum+Number(item.dataset.value),0);$('.selection-summary').textContent=selected.length?'已选 '+selected.map(item=>item.dataset.name).join('、')+' · 合计 '+total:'尚未选择';say('当前选择 '+selected.length+' 项');});}
  if(key==="chart-7"){const chart=$('.lasso-chart'),box=$('.lasso-box');let start=null;chart.onpointerdown=e=>{if(e.target.closest('button'))return;const r=chart.getBoundingClientRect();start={x:e.clientX-r.left,y:e.clientY-r.top};chart.setPointerCapture(e.pointerId);Object.assign(box.style,{left:start.x+'px',top:start.y+'px',width:'0',height:'0'});};chart.onpointermove=e=>{if(!start||!chart.hasPointerCapture(e.pointerId))return;const r=chart.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;Object.assign(box.style,{left:Math.min(start.x,x)+'px',top:Math.min(start.y,y)+'px',width:Math.abs(x-start.x)+'px',height:Math.abs(y-start.y)+'px'});};chart.onpointerup=e=>{if(!start)return;chart.releasePointerCapture(e.pointerId);const selection=box.getBoundingClientRect(),svg=$('svg').getBoundingClientRect();let count=0;$$('[data-point]').forEach(point=>{const cx=svg.left+Number(point.getAttribute('cx'))/300*svg.width,cy=svg.top+Number(point.getAttribute('cy'))/170*svg.height,inside=cx>=selection.left&&cx<=selection.right&&cy>=selection.top&&cy<=selection.bottom;point.classList.toggle('selected',inside);if(inside)count++;});$('.selection-count').textContent='已选 '+count+' 个点';say('套索选中了 '+count+' 个点');start=null;};$('.clear-selection').onclick=()=>{$$('[data-point]').forEach(p=>p.classList.remove('selected'));box.removeAttribute('style');$('.selection-count').textContent='已选 0 个点';say('已清除选择');};}
  if(key==="chart-8") bindPanZoom(root,say);
  if(key==="chart-9"){const inputs=$$('.dual-range input'),label=$('.range-chart p'),update=changed=>{let start=Number(inputs[0].value),end=Number(inputs[1].value);if(start>=end){if(changed===inputs[0])start=end-1;else end=start+1;inputs[0].value=start;inputs[1].value=end;}label.textContent=start+' 月 — '+end+' 月';root.style.setProperty('--range-start',((start-1)/11*100)+'%');root.style.setProperty('--range-end',((end-1)/11*100)+'%');say('当前范围：'+label.textContent);};inputs.forEach(input=>input.oninput=()=>update(input));update();}
  if(key==="chart-10"){$$('[data-link]').forEach(el=>{const activate=()=>{const id=el.dataset.link;root.dataset.active=id;say('已联动高亮：'+({a:'自然流量',b:'付费投放',c:'活动'})[id]);};el.onpointerenter=activate;el.onclick=activate;});}
  if(key==="chart-11"){$$('[data-filter]').forEach(b=>b.onclick=()=>{root.dataset.filter=b.dataset.filter;$('.filter-chip').textContent=b.dataset.filter;$('.filter-summary b').textContent=b.dataset.filter+' · '+(b.dataset.filter==='华东'?'126':b.dataset.filter==='华南'?'94':'66')+' 万';say('整张看板已筛选：'+b.dataset.filter);});$('.clear-filter').onclick=()=>{delete root.dataset.filter;$('.filter-chip').textContent='全部地区';$('.filter-summary b').textContent='总量 286 万';say('已清除跨图筛选');};}
  if(key==="chart-12") makeContextWindow(root,say);
  if(key==="chart-13"){$$('[data-label]').forEach(point=>point.onclick=()=>{const active=point.classList.toggle('annotated');$('.annotation-note').textContent=active?'标注：'+point.dataset.label:'点击数据点添加标注';say(active?'已添加标注：'+point.dataset.label:'已移除标注');});}
  if(key==="chart-14"){$$('[data-period]').forEach(b=>b.onclick=()=>{$$('[data-period]').forEach(x=>x.classList.remove('active'));b.classList.add('active');root.dataset.period=b.dataset.period;$('.delta-label').textContent='本期较'+b.dataset.period+' '+(b.dataset.period==='同比'?'+12.4%':'+3.8%');say('已切换到'+b.dataset.period);});}
  if(key==="chart-15"){$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');root.dataset.view=b.dataset.view;say('已切换为'+b.textContent+'视图');});}
  if(key==="chart-16"){$$('[data-month]').forEach(point=>point.onclick=()=>{const active=!point.classList.contains('selected');$$('[data-month]').forEach(p=>p.classList.remove('selected'));point.classList.toggle('selected',active);$('.pinned-tip').textContent=active?point.dataset.month+' · '+point.dataset.value:'点击数据点固定提示';say(active?'提示框已固定':'提示框已关闭');});}
  if(key==="chart-17"){$$('.sync-panel').forEach(panel=>panel.onpointermove=e=>{const r=panel.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));root.style.setProperty('--sync-x',(ratio*100)+'%');$('.shared-cursor>span').textContent=(Math.round(ratio*11)+1)+' 月';root.classList.add('syncing');});root.onpointerleave=()=>root.classList.remove('syncing');}
  if(key==="chart-18") bindPlayback(root,say);
  if(key==="chart-19") bindHistory(root,say);
  if(key==="chart-20") bindHierarchy(root,say);
  if(key==="chart-21") bindNetwork(root,say);
  if(key==="chart-22"){$$('[data-node]').forEach(node=>{const activate=()=>{root.dataset.flow=node.dataset.node;say('正在追踪：'+node.dataset.node);};node.onpointerenter=activate;node.onclick=activate;});}
  if(key==="chart-23"){$$('[data-region]').forEach(region=>{const show=()=>{$$('[data-region]').forEach(x=>x.classList.remove('selected'));region.classList.add('selected');$('.map-tip').textContent=region.dataset.region+' · 活跃用户 '+({华北:'42K',华东:'86K',华南:'68K'})[region.dataset.region];say('已拾取：'+region.dataset.region);};region.onpointerenter=show;region.onclick=show;});}
  if(key==="chart-24"){$$('[data-detail]').forEach(bar=>bar.onclick=()=>{$$('[data-detail]').forEach(x=>x.classList.remove('selected'));bar.classList.add('selected');$('.detail-link span').textContent='已选择：'+bar.dataset.detail;const button=$('.detail-link button');button.disabled=false;button.dataset.region=bar.dataset.detail;say('可进入 '+bar.dataset.detail+' 明细');});$('.detail-link button').onclick=()=>say('将携带 '+$('.detail-link button').dataset.region+' 和当前筛选进入明细');}
  if(key==="chart-25") bindKeyboardChart(root,say);
  if(key==="chart-26"){const input=$('.whatif-chart input'),budget=$('.whatif-chart label b'),revenue=$('.forecast-card strong'),meta=$('.forecast-card em');input.oninput=()=>{const value=Number(input.value),forecast=Math.round(value*(2.6+value/125));budget.textContent=value+' 万';revenue.textContent=forecast+' 万';meta.textContent='模拟结果 · ROI '+(forecast/value).toFixed(1);say('预算 '+value+' 万，预测收入 '+forecast+' 万');};}
  if(key==="chart-27"){$$('[data-dimension]').forEach(button=>button.onclick=()=>{const labels={地区:['华东','华南','华北'],渠道:['自然','投放','活动'],品类:['服饰','数码','家居']}[button.dataset.dimension];$$('[data-dimension]').forEach(x=>x.classList.toggle('active',x===button));$$('.switch-bars span').forEach((span,i)=>span.textContent=labels[i]);$('.dimension-switch p').textContent='成交额 · 按'+button.dataset.dimension;say('已切换为'+button.dataset.dimension+'维度');});}
  if(key==="chart-28"){$$('[data-metric]').forEach(button=>button.onclick=()=>{const values={收入:['286 万元','收入'],订单量:['1,842 单','订单量'],转化率:['6.8%','转化率']}[button.dataset.metric];$$('[data-metric]').forEach(x=>x.classList.toggle('active',x===button));$('.metric-readout span').textContent='当前指标 · '+values[1];$('.metric-readout b').textContent=values[0];say('已切换到'+values[1]);});}
  if(key==="chart-29"){$$('[data-grain]').forEach(button=>button.onclick=()=>{const counts={日:30,周:8,月:12};$$('[data-grain]').forEach(x=>x.classList.toggle('active',x===button));$('.granularity-chart p').textContent='按'+button.dataset.grain+'聚合 · 共 '+counts[button.dataset.grain]+' 个数据点';say('已按'+button.dataset.grain+'重新聚合');});}
  if(key==="chart-30") makeBrushDetails(root,say);
  if(key==="chart-31"){$('.label-head button').onclick=()=>{const button=$('.label-head button'),show=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',show);button.textContent=show?'隐藏关键标签':'显示关键标签';root.classList.toggle('show-labels',show);say(show?'已显示峰值和关键标签':'已隐藏数据标签');};}
  if(key==="table-0") bindTableSort(root,say);
  if(key==="table-1") bindTableFilter(root,say);
  if(key==="table-2") bindBulkTable(root,say);
  if(key==="table-3"){$$('[data-row]').forEach(button=>button.onclick=()=>{const row=$(`[data-detail-row="${button.dataset.row}"]`),open=!row.classList.contains('open');$$('.row-detail').forEach(x=>x.classList.remove('open'));$$('[data-row]').forEach(x=>x.textContent='›');row.classList.toggle('open',open);button.textContent=open?'⌄':'›';say(open?'已展开当前行详情':'已收起详情');});}
  if(key==="table-4"){const actions=$('.edit-actions'),input=$('.edit-actions input'),value=$('.editable-value');$('.edit-cell').onclick=()=>{actions.classList.add('open');input.value=value.textContent;input.focus();say('正在编辑负责人');};$('[data-edit="save"]').onclick=()=>{if(!input.value.trim()){say('负责人不能为空');return;}value.textContent=input.value.trim();actions.classList.remove('open');say('已保存负责人：'+value.textContent);};$('[data-edit="cancel"]').onclick=()=>{actions.classList.remove('open');say('已取消修改');};}
  if(key==="table-5") bindColumnResize(root,say);
  if(key==="table-6"){$('.wide-table').onscroll=()=>say('已横向滚动，业务线列保持固定');}
  if(key==="table-7"){let page=1;$$('[data-page]').forEach(button=>button.onclick=()=>{page=Math.max(1,Math.min(8,page+(button.dataset.page==='next'?1:-1)));$('.pagination b').textContent=page+' / 8';say('已切换到第 '+page+' 页');});}
  if(key==="filter-0"){$$('[data-quick]').forEach(button=>button.onclick=()=>{const status=button.dataset.quick;$$('[data-quick]').forEach(x=>x.classList.toggle('active',x===button));let count=0;$$('.quick-filter li').forEach(row=>{const visible=status==='全部'||row.dataset.status===status;row.hidden=!visible;if(visible)count++;});$('.quick-filter p').textContent='共 '+count+' 条';say('已筛选：'+status);});}
  if(key==="filter-1"){$$('.logic-toggle button').forEach(button=>button.onclick=()=>{$$('.logic-toggle button').forEach(x=>x.classList.toggle('active',x===button));$('.builder-filter p').textContent='符合'+(button.textContent==='AND'?'全部':'任一')+'条件';say('已切换为 '+button.textContent+' 逻辑');});bindCycleButtons($$('.condition [data-values]'),say);$('.add-condition').onclick=()=>{const condition=$('.condition').cloneNode(true);condition.querySelector('.remove-condition').onclick=()=>{condition.remove();say('已删除条件');};$('.add-condition').before(condition);bindCycleButtons([...condition.querySelectorAll('[data-values]')],say);say('已添加一条条件');};$('.remove-condition').onclick=e=>{if($$('.condition').length>1)e.currentTarget.closest('.condition').remove();else say('至少保留一条条件');};}
  if(key==="filter-2"){bindCycleButtons($$('.global-controls [data-values]'),text=>{const controls=$$('.global-controls button').map(x=>x.textContent);$('.global-filter p').textContent=controls.join(' · ');const factor=controls.includes('华东')?.72:controls.includes('华南')?.58:1;$('.global-cards article:first-child b').textContent=Math.round(286*factor)+' 万';say('全局条件已更新，全部卡片同步刷新');});}
  if(key==="filter-3"){$$('[data-tag]').forEach(button=>button.onclick=()=>{button.remove();updateFilterTags(root,say);});$('.clear-tags').onclick=()=>{$$('[data-tag]').forEach(x=>x.remove());updateFilterTags(root,say);};}
  if(key==="filter-4"){$$('[data-view-name]').forEach(button=>button.onclick=()=>{$$('[data-view-name]').forEach(x=>x.classList.toggle('active',x===button));$('.saved-view p').textContent=button.dataset.viewName==='华东周报'?'地区：华东 · 本周':button.dataset.viewName==='待跟进项目'?'状态：待处理 · 按更新时间排序':'地区：全国 · 近 30 天';say('已恢复视图：'+button.dataset.viewName);});$('.save-current').onclick=()=>say('当前筛选、排序与列配置已保存');}
  if(key==="filter-5"){$$('[data-time]').forEach(button=>button.onclick=()=>{$$('[data-time]').forEach(x=>x.classList.toggle('active',x===button));$('.refresh-state span').textContent='自动刷新中 · 最近 '+button.dataset.time;say('时间范围已切换为最近 '+button.dataset.time);});}
  if(key==="filter-6"){let draft='';const apply=$('[data-dirty="apply"]'),reset=$('[data-dirty="reset"]');$$('[data-draft]').forEach(button=>button.onclick=()=>{draft=button.dataset.draft;$$('[data-draft]').forEach(x=>x.classList.toggle('active',x===button));apply.disabled=reset.disabled=false;$('.dirty-filter p').textContent='有未应用修改：'+draft;say('已修改草稿，点击应用后才会更新数据');});apply.onclick=()=>{$('.dirty-head span').textContent='已应用：'+draft;apply.disabled=reset.disabled=true;$('.dirty-filter p').textContent='当前显示'+draft+'数据';say('筛选已应用：'+draft);};reset.onclick=()=>{draft='';$$('[data-draft]').forEach(x=>x.classList.remove('active'));apply.disabled=reset.disabled=true;$('.dirty-filter p').textContent='已恢复到当前生效条件';say('未应用修改已重置');};}
  if(type==="dashboard"){$$('button:not([data-values])').forEach(b=>b.onclick=()=>{root.querySelectorAll('.focused').forEach(x=>x.classList.remove('focused'));b.classList.add('focused');say(`已聚焦：${b.textContent.trim()}`);});bindCycleButtons($$('[data-values]'),say);}
}

function bindTableSort(root,say){const button=root.querySelector('[data-sort]'),body=root.querySelector('tbody'),original=[...body.rows],states=['default','asc','desc'];let index=0;button.onclick=()=>{index=(index+1)%3;const state=states[index],rows=state==='default'?original:[...original].sort((a,b)=>(Number(a.dataset.value)-Number(b.dataset.value))*(state==='asc'?1:-1));rows.forEach(row=>body.append(row));button.querySelector('i').textContent=state==='asc'?'↑':state==='desc'?'↓':'↕';say(state==='default'?'已恢复默认顺序':'收入已'+(state==='asc'?'升序':'降序')+'排列');};}
function bindTableFilter(root,say){const menu=root.querySelector('.filter-menu'),trigger=root.querySelector('.table-filter-head button');trigger.onclick=()=>menu.classList.toggle('open');root.querySelectorAll('[data-status]').forEach(button=>button.onclick=()=>{const status=button.dataset.status;let count=0;root.querySelectorAll('tbody tr').forEach(row=>{const visible=status==='全部'||row.dataset.status===status;row.hidden=!visible;if(visible)count++;});trigger.textContent='状态：'+status+' ⌄';menu.classList.remove('open');root.querySelector('p').textContent='共 '+count+' 条';say('已筛选：'+status);});}
function bindBulkTable(root,say){const checks=[...root.querySelectorAll('input')],bar=root.querySelector('.bulk-bar'),button=bar.querySelector('button'),update=()=>{const count=checks.filter(x=>x.checked).length;bar.querySelector('span').textContent=count?'已选 '+count+' 条':'选择记录后可批量操作';button.disabled=!count;say(count?'已选择 '+count+' 条记录':'未选择记录');};checks.forEach(check=>check.onchange=update);button.onclick=()=>{checks.forEach(x=>x.checked=false);update();say('批量归档完成（演示）');};}
function bindColumnResize(root,say){const column=root.querySelector('.resize-col'),handle=column.querySelector('button'),label=root.querySelector('p');let start=0,width=0;handle.onpointerdown=e=>{start=e.clientX;width=column.offsetWidth;handle.setPointerCapture(e.pointerId);};handle.onpointermove=e=>{if(!handle.hasPointerCapture(e.pointerId))return;const next=Math.max(95,Math.min(210,width+e.clientX-start));column.style.width=next+'px';root.querySelector('.resize-table-wrap').style.gridTemplateColumns=next+'px 1fr 1fr';label.textContent='拖动表头分隔线 · '+Math.round(next)+' px';};handle.onpointerup=e=>{handle.releasePointerCapture(e.pointerId);say('列宽已保存为 '+Math.round(column.offsetWidth)+' px');};}
function makeBrushDetails(root,say){const chart=root.querySelector('.mini-brush'),range=root.querySelector('.brush-window'),rows=root.querySelector('.detail-rows'),label=root.querySelector('p');let start=null;chart.onpointerdown=e=>{const r=chart.getBoundingClientRect();start=e.clientX-r.left;chart.setPointerCapture(e.pointerId);range.style.left=start+'px';range.style.width='0';};chart.onpointermove=e=>{if(start===null||!chart.hasPointerCapture(e.pointerId))return;const x=e.clientX-chart.getBoundingClientRect().left;range.style.left=Math.min(start,x)+'px';range.style.width=Math.abs(x-start)+'px';};chart.onpointerup=e=>{chart.releasePointerCapture(e.pointerId);start=null;rows.classList.add('filtered');label.textContent='选区命中 2 条明细';say('图表选区已联动下方 2 条明细');};}
function updateFilterTags(root,say){const count=root.querySelectorAll('[data-tag]').length;root.querySelector('.filter-result b').textContent=count?String(35+count*17):'286';root.querySelector('.filter-result span').textContent=count?'条匹配记录':'条全部记录';say(count?'当前还有 '+count+' 个筛选条件':'已清空全部条件');}

function bindCascader(root,say){
  const $=selector=>root.querySelector(selector), $$=selector=>[...root.querySelectorAll(selector)];
  const state={province:0,city:0,area:null};
  const result=$('.demo-result'),search=$('.cascade-search'),matches=$('.cascade-matches');
  const path=()=>[locationTree[state.province].name,locationTree[state.province].children[state.city].name,state.area].filter(Boolean);
  const render=()=>{
    const province=locationTree[state.province],city=province.children[state.city];
    $('.provinces').innerHTML=locationTree.map((p,i)=>`<button data-province="${i}" class="${i===state.province?'chosen':''}">${p.name}<b>›</b></button>`).join('');
    $('.cities').innerHTML=province.children.map((c,i)=>`<button data-city="${i}" class="${i===state.city?'chosen':''}">${c.name}<b>›</b></button>`).join('');
    $('.areas').innerHTML=city.children.map(area=>`<button data-area="${area}" class="${area===state.area?'chosen':''}">${area}</button>`).join('');
    $$('[data-province]').forEach(b=>b.onclick=()=>{state.province=Number(b.dataset.province);state.city=0;state.area=null;render();result.textContent=`当前选择：${locationTree[state.province].name}`;say('上级已切换，下级选项已更新');});
    $$('[data-city]').forEach(b=>b.onclick=()=>{state.city=Number(b.dataset.city);state.area=null;render();result.textContent=`当前选择：${path().join(' / ')}`;say('城市已切换，区县选项已更新');});
    $$('[data-area]').forEach(b=>b.onclick=()=>{state.area=b.dataset.area;render();result.textContent=`已选择：${path().join(' / ')}`;say(`已选择：${state.area}`);});
  };
  const showMatches=paths=>{matches.innerHTML=paths.length?pathButtons(paths):'<p>没有匹配地区</p>';matches.classList.add('show');$$('.cascade-matches button').forEach(b=>b.onclick=()=>{const selected=b.dataset.path.split('|'),pIndex=locationTree.findIndex(p=>p.name===selected[0]);state.province=pIndex;state.city=locationTree[pIndex].children.findIndex(c=>c.name===selected[1]);state.area=selected[2];search.value=selected.at(-1);matches.classList.remove('show');render();result.textContent=`已选择：${selected.join(' / ')}`;say(`已匹配并选择：${selected.at(-1)}`);});};
  search.oninput=()=>{const keyword=search.value.trim().toLowerCase();if(!keyword){matches.classList.remove('show');return;}showMatches(locationPaths.filter(item=>item.join(' ').toLowerCase().includes(keyword)));};
  search.onfocus=()=>{if(search.value.trim())search.oninput();};
  render();
}

function bindCycleButtons(buttons,say){buttons.forEach(button=>button.onclick=()=>{const values=button.dataset.values.split('|'),next=(values.indexOf(button.textContent.trim())+1)%values.length;button.textContent=values[next];say(`已切换为：${values[next].replace('⌄','')}`);});}
function bindPanZoom(root,say){let scale=1,offset=0;const windowEl=root.querySelector('.panzoom-window'),label=root.querySelector('.panzoom-chart p'),apply=()=>{windowEl.style.setProperty('--scale',scale);windowEl.style.setProperty('--offset',offset+'px');const months=Math.max(3,Math.round(6/scale)),start=Math.max(1,Math.min(12-months+1,1+Math.round(-offset/35)));label.textContent='当前范围：'+start+' 月 — '+(start+months-1)+' 月';say(label.textContent);};root.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>{const action=button.dataset.action;if(action==='in')scale=Math.min(2,scale+.25);if(action==='out')scale=Math.max(1,scale-.25);if(action==='left')offset=Math.min(0,offset+35);if(action==='right')offset=Math.max(-210,offset-35);if(action==='reset'){scale=1;offset=0;}apply();});let startX=null;windowEl.onpointerdown=e=>{startX=e.clientX;windowEl.setPointerCapture(e.pointerId);};windowEl.onpointermove=e=>{if(startX===null||!windowEl.hasPointerCapture(e.pointerId))return;offset=Math.max(-210,Math.min(0,offset+e.clientX-startX));startX=e.clientX;apply();};windowEl.onpointerup=e=>{windowEl.releasePointerCapture(e.pointerId);startX=null;};apply();}
function makeContextWindow(root,say){const selection=root.querySelector('.context-selection'),title=root.querySelector('.focus-title'),track=root.querySelector('.context-track');let start=null;selection.onpointerdown=e=>{start=e.clientX;selection.setPointerCapture(e.pointerId);};selection.onpointermove=e=>{if(start===null||!selection.hasPointerCapture(e.pointerId))return;const max=track.clientWidth-selection.offsetWidth,left=Math.max(0,Math.min(max,selection.offsetLeft+e.clientX-start));selection.style.left=left+'px';start=e.clientX;const month=Math.round(left/Math.max(1,max)*5)+1;title.textContent='主图 · '+month+' 月至 '+(month+6)+' 月';say('上下文窗口已移动到 '+month+' 月至 '+(month+6)+' 月');};selection.onpointerup=e=>{selection.releasePointerCapture(e.pointerId);start=null;};}
function bindPlayback(root,say){const input=root.querySelector('input'),label=root.querySelector('.playback-controls b'),button=root.querySelector('.play-toggle'),bars=[...root.querySelectorAll('.playback-bars i')];let timer=null;const update=()=>{const step=Number(input.value);label.textContent=(step+1)+' 月';bars.forEach((bar,i)=>bar.classList.toggle('current',i===step));say('当前播放到 '+label.textContent);};const stop=()=>{clearInterval(timer);timer=null;button.textContent='▶';};button.onclick=()=>{if(timer){stop();say('已暂停');return;}button.textContent='Ⅱ';timer=setInterval(()=>{input.value=(Number(input.value)+1)%5;update();},500);say('开始播放');};input.oninput=()=>{stop();update();};update();}
function bindHistory(root,say){const states=['初始视图'],future=[],$=selector=>root.querySelector(selector),update=()=>{$('[data-history="undo"]').disabled=states.length===1;$('[data-history="redo"]').disabled=future.length===0;$('.history-chart p').textContent=states.at(-1);};root.querySelectorAll('.history-bars button').forEach(button=>button.onclick=()=>{states.push('筛选：'+button.dataset.value);future.length=0;root.dataset.selected=button.dataset.value;say(states.at(-1));update();});$('[data-history="undo"]').onclick=()=>{if(states.length>1){future.push(states.pop());delete root.dataset.selected;say('已撤销');update();}};$('[data-history="redo"]').onclick=()=>{if(future.length){states.push(future.pop());say('已重做');update();}};$('[data-history="reset"]').onclick=()=>{states.splice(1);future.length=0;delete root.dataset.selected;say('已恢复初始视图');update();};update();}
function bindHierarchy(root,say){const crumb=root.querySelector('.hierarchy-crumb'),tree=root.querySelector('.treemap'),data={电商:['服饰','数码','家居'],广告:['搜索','信息流','品牌'],服务:['咨询','交付','续费']};const renderRoot=()=>{crumb.querySelector('span').textContent='';tree.innerHTML='<button data-node="电商" class="tree-a">电商</button><button data-node="广告" class="tree-b">广告</button><button data-node="服务" class="tree-c">服务</button>';bindNodes();};const bindNodes=()=>tree.querySelectorAll('[data-node]').forEach(button=>button.onclick=()=>{const children=data[button.dataset.node];if(!children)return;crumb.querySelector('span').textContent='› '+button.dataset.node;tree.innerHTML=children.map((name,i)=>'<button class="tree-'+String.fromCharCode(97+i)+'">'+name+'</button>').join('');say('已放大到：'+button.dataset.node);});crumb.querySelector('button').onclick=()=>{renderRoot();say('已返回全部业务');};renderRoot();}
function bindNetwork(root,say){const nodes=[...root.querySelectorAll('[data-node]')],edges=[...root.querySelectorAll('[data-edge]')],adjacent={a:['a','b','c'],b:['a','b','d'],c:['a','c'],d:['b','d']};nodes.forEach(node=>node.onclick=()=>{const id=node.dataset.node;root.dataset.focus=id;nodes.forEach(n=>n.classList.toggle('dim',!adjacent[id].includes(n.dataset.node)));edges.forEach(edge=>edge.classList.toggle('dim',!edge.dataset.edge.includes(id)));say('已聚焦节点 '+id.toUpperCase()+' 及其直接邻居');});root.querySelector('svg').onclick=e=>{if(e.target.tagName==='svg'){delete root.dataset.focus;nodes.forEach(n=>n.classList.remove('dim'));edges.forEach(edge=>edge.classList.remove('dim'));say('已恢复全部关系');}};}
function bindKeyboardChart(root,say){const bars=[...root.querySelectorAll('[data-index]')];let index=0;const focus=()=>{bars.forEach((bar,i)=>bar.classList.toggle('focused',i===index));bars[index].focus();say('当前 '+bars[index].textContent);};root.onkeydown=e=>{if(e.key==='ArrowRight'){e.preventDefault();index=(index+1)%bars.length;focus();}if(e.key==='ArrowLeft'){e.preventDefault();index=(index-1+bars.length)%bars.length;focus();}if(e.key==='Enter'){bars[index].classList.toggle('selected');say(bars[index].textContent+(bars[index].classList.contains('selected')?' 已选择':' 已取消'));}if(e.key==='Escape'){bars.forEach(b=>b.classList.remove('selected','focused'));say('已清除选择');}};bars.forEach((bar,i)=>bar.onclick=()=>{index=i;focus();});root.focus();focus();}

function makeDraggable(el,bounds,onDrop){let startX=0,startY=0;el.onpointerdown=e=>{e.preventDefault();startX=e.clientX;startY=e.clientY;el.setPointerCapture(e.pointerId);el.classList.add('dragging');};el.onpointermove=e=>{if(!el.hasPointerCapture(e.pointerId))return;el.style.transform=`translate(${e.clientX-startX}px,${e.clientY-startY}px)`;};el.onpointerup=e=>{if(!el.hasPointerCapture(e.pointerId))return;el.releasePointerCapture(e.pointerId);el.classList.remove('dragging');el.style.transform='';onDrop(e.clientX,e.clientY);};}
function makeSortable(list,say){let dragged=null;[...list.children].forEach(item=>{item.onpointerdown=e=>{dragged=item;item.setPointerCapture(e.pointerId);item.classList.add('dragging');};item.onpointermove=e=>{if(!dragged)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.sortable-list button');if(target&&target!==dragged)list.insertBefore(dragged,e.clientY<target.getBoundingClientRect().top+target.offsetHeight/2?target:target.nextSibling);};item.onpointerup=e=>{item.releasePointerCapture(e.pointerId);item.classList.remove('dragging');dragged=null;say('顺序已更新，可继续拖动');};});}
function makeFreeMove(node,canvas,say){node.onpointerdown=e=>{node.setPointerCapture(e.pointerId);node.dataset.dx=e.clientX-node.offsetLeft;node.dataset.dy=e.clientY-node.offsetTop;};node.onpointermove=e=>{if(!node.hasPointerCapture(e.pointerId))return;const x=Math.max(0,Math.min(canvas.clientWidth-node.offsetWidth,e.clientX-Number(node.dataset.dx))),y=Math.max(0,Math.min(canvas.clientHeight-node.offsetHeight,e.clientY-Number(node.dataset.dy)));node.style.left=`${x}px`;node.style.top=`${y}px`;canvas.classList.toggle('aligned',Math.abs(x-(canvas.clientWidth-node.offsetWidth)/2)<12);};node.onpointerup=e=>{node.releasePointerCapture(e.pointerId);say(canvas.classList.contains('aligned')?'已吸附到中心参考线':'节点位置已更新');};}
function makeResize(box,handle,say){handle.onpointerdown=e=>{e.preventDefault();handle.setPointerCapture(e.pointerId);handle.dataset.x=e.clientX;handle.dataset.y=e.clientY;handle.dataset.w=box.offsetWidth;handle.dataset.h=box.offsetHeight;};handle.onpointermove=e=>{if(!handle.hasPointerCapture(e.pointerId))return;const w=Math.max(140,Math.min(260,Number(handle.dataset.w)+e.clientX-Number(handle.dataset.x))),h=Math.max(80,Math.min(160,Number(handle.dataset.h)+e.clientY-Number(handle.dataset.y)));box.style.width=`${w}px`;box.style.height=`${h}px`;box.querySelector('.size-label').textContent=`${Math.round(w)} × ${Math.round(h)}`;};handle.onpointerup=e=>{handle.releasePointerCapture(e.pointerId);say(`尺寸已调整为 ${box.querySelector('.size-label').textContent}`);};}
function runProgress(root,say){const bar=root.querySelector('.progress-demo i'),label=root.querySelector('.progress-demo span');bar.style.width='0';let n=0;const timer=setInterval(()=>{n+=4;bar.style.width=`${n}%`;label.textContent=`${n}%`;if(n>=100){clearInterval(timer);say('导入完成');}},35);}
function makeBrush(chart,say){let start=0;const range=chart.querySelector('.brush-range');chart.onpointerdown=e=>{const r=chart.getBoundingClientRect();start=e.clientX-r.left;chart.setPointerCapture(e.pointerId);range.style.left=`${start}px`;range.style.width='0';};chart.onpointermove=e=>{if(!chart.hasPointerCapture(e.pointerId))return;const x=e.clientX-chart.getBoundingClientRect().left;range.style.left=`${Math.min(start,x)}px`;range.style.width=`${Math.abs(x-start)}px`;};chart.onpointerup=e=>{chart.releasePointerCapture(e.pointerId);say('已放大所选时间范围');};chart.querySelector('button').onclick=()=>{range.style.width='0';say('已恢复全部范围');};}
function drill(root,region,say){root.querySelector('.drill-crumb span').textContent=`› ${region}`;const names=region==='华东'?['上海','浙江','江苏']:region==='华南'?['广东','福建','海南']:['北京','河北','山东'];root.querySelector('.drill-bars').innerHTML=names.map((name,i)=>`<button style="--h:${75-i*15}%">${name}</button>`).join('');say(`已下钻到：${region}`);}

function copyText(text){navigator.clipboard?.writeText(text).then(showToast).catch(()=>{const input=document.createElement("textarea");input.value=text;document.body.append(input);input.select();document.execCommand("copy");input.remove();showToast();});}
function showToast(){const toast=document.querySelector("#toast");toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),1300);}
document.querySelectorAll("[data-copy]").forEach(button=>button.addEventListener("click",()=>copyText(button.dataset.copy)));
const searchDialog=document.querySelector('#search-dialog'),globalSearch=document.querySelector('#global-search'),searchResults=document.querySelector('#search-results');
function renderSearch(query=''){const keyword=query.trim().toLowerCase(),tokens=keyword.split(/\s+/).filter(Boolean),results=(keyword==='__favorites__'?searchIndex.filter(item=>favorites.has(itemId(item.groupIndex,item.itemIndex))):keyword==='__recent__'?recent.map(id=>{const [groupIndex,itemIndex]=id.split('-').map(Number);return searchIndex.find(item=>item.groupIndex===groupIndex&&item.itemIndex===itemIndex);}).filter(Boolean):keyword?searchIndex.filter(item=>{const text=[item.name,item.en,item.when,item.group,item.category].join(' ').toLowerCase();return tokens.some(token=>text.includes(token));}):searchIndex.slice(0,8)).slice(0,16);searchResults.innerHTML=results.length?results.map(item=>`<button data-search-go="${item.groupIndex}-${item.itemIndex}"><span><b>${item.name}</b><small>${item.en}</small></span><em>${item.group} · ${item.category}</em></button>`).join(''):`<p>${keyword==='__favorites__'?'还没有收藏组件':keyword==='__recent__'?'还没有浏览记录':'没有找到相关组件'}</p>`;searchResults.querySelectorAll('[data-search-go]').forEach(button=>button.onclick=()=>{[currentGroup,currentItem]=button.dataset.searchGo.split('-').map(Number);closeSearch();render();window.scrollTo({top:document.querySelector('.content').offsetTop-75,behavior:'smooth'});});}
function openSearch(){searchDialog.hidden=false;renderSearch();requestAnimationFrame(()=>{searchDialog.classList.add('open');globalSearch.focus();});}
function closeSearch(){searchDialog.classList.remove('open');setTimeout(()=>searchDialog.hidden=true,150);}
document.querySelector('#search-trigger').onclick=openSearch;globalSearch.oninput=()=>renderSearch(globalSearch.value);searchDialog.onclick=e=>{if(e.target===searchDialog)closeSearch();};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch();}if(e.key==='Escape'&&!searchDialog.hidden)closeSearch();});
document.querySelector('#library-count').textContent=searchIndex.length+' 个模式';
document.querySelectorAll('[data-task]').forEach(button=>button.onclick=()=>{openSearch();const query=taskQueries[button.dataset.task];globalSearch.value=query.startsWith('__')?'':query;renderSearch(query);});
render();
